### ISSUE TITLE
Follow the XDG base directory specification

### ISSUE THREAD

**Issue by arcresu** [jakubroztocil/httpie#145]
Instead of using config at `$HOME/.httpie`, the default should be `${XDG_CONFIG_HOME:-$HOME/.config}/httpie` for unix-based operating systems according to [the XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

As well as keeping the home directory clean, the semantic separation of config, runtime data, cache data and user-local software by the spec is helpful to users and other tools (e.g. backup software).

In terms of migration, I would suggest using the xdg-compilant config location if it exists and falling back to the current default location. This would also negate the need for the `$HTTPIE_CONFIG_DIR` variable, so it could be removed/de-emphasised from the documentation but still checked for at least a few versions for compatibility.

**Comment by mkwmms** [comment]
huge :+1: for this

**Comment by skmlcd** [comment]
There is already a pull request for this. Any reason against this change?

**Comment by bitti** [comment]
Yeah, it doesn't make much sense to trade less $HOME directory clutter for more environment setup  clutter, so just changing the default is the way to go.
