### ISSUE TITLE
support http over unix domain sockets

### ISSUE THREAD

**Issue by monsanto** [jakubroztocil/httpie#209]
For security reasons, some of my HTTP services need to run on a unix domain socket so I can protect them using filesystem permissions. It would be useful if I could use httpie for testing these services.

docker-py uses the requests library and has support for this--see https://github.com/dotcloud/docker-py/blob/master/docker/unixconn/unixconn.py for the (small) implementation, and https://github.com/dotcloud/docker-py/blob/master/docker/client.py#L90 for how they extend requests using `self.mount`.

**Comment by jakubroztocil** [comment]
Implemented as as plugin (supported by HTTPie v0.9.1+): [httpie-unixsocket](https://github.com/msabramo/httpie-unixsocket)
