### ISSUE TITLE
Adding cookie to cookiejar (or allowing multiple Cookie: headers)

### ISSUE THREAD

**Issue by droope** [jakubroztocil/httpie#214]
Hi there,

I am having issues with httpie in a rather contrived use-case. I was hoping that I perhaps help people solve this issue in the future or rather get some suggestions on how to solve it myself.

The issue arises when a server expects a cookie set by the client side using JS. In order to work around this, I need to add a cookie with a static value to my session. I was hoping to do so in a way similar to this.

```
#!/bin/bash
                                                                                                                                         . include.sh

function accept_terms {
    email="john_ra+86@zoho.com"                                                                                                                                     
    # login
    #http $sess https://coinbase.com/signin
    csrf_token=`http $sess https://site.com/signin | grep 'csrf-token' | awk -F'"' '{print $2}' | awk -F'"' '{print $1}'`

   # this line below >>>
    http $sess -f POST https://site.com/sessions "Cookie:df=579d23557fc4619cb01656425512a9db" "utf8=%E2%9C%93" "authenticity_token=$csrf_token" "email=$email" "pas#

    # accept terms
    http $sess -f POST https://site.com/users/accept_terms "_method=post" "authenticity_token=$csrf_token"
}

accept_terms
```

In the line where I set the cookie header, httpie replaces the session cookie with the cookie I manually set. I've checked and if I were allowed to put two cookie headers apache would accept it, albeit a method to embed a custom cookie into the cookiejar might be a bit tidier!

Thanks,
Pedro

**Comment by jakubroztocil** [comment]
I’m pretty sure this has been resolved in current `master`.

**Comment by droope** [comment]
Awesome, thank you.
