### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by dequis** [jakubroztocil/httpie#248]
I find myself doing "man http" very often, and IT'S NOT THERE, oh no

And having to visit github to view documentation is... not very ideal.

Could use `rst2man` to generate one man page, but it supports a more limited amount of markup so it failed to parse the README when i tried.

**Comment by merwok** [comment]
Duplicate of #477 

Related to #448 (would not be confusing that the dev repo shows dev docs if people using the released version don’t need to come to github to see docs)

**Comment by dequis** [comment]
Duplicate of #477 

Seems to be more active and about the same thing so i'm closing this one
