### ISSUE TITLE
When "Content-Type:" is NOT set to 'application/json', but it IS JSON httpie doesn't do formatting

### ISSUE THREAD

**Issue by Restuta** [jakubroztocil/httpie#261]
I understand that this sounds like a bad API, but some 3rd parities seem not to care about putting correct  content type, it would be nice to have a way to force `httpie` to still apply JSON formatting. Or maybe there is?

![httpie](https://cloud.githubusercontent.com/assets/377261/4408957/b50be97a-44d8-11e4-91e9-92ca60ef09eb.png)

**Comment by jakubroztocil** [comment]
Sorry, there is no support for this. You can use this as a workaround:

```bash
http httpbin.org/get | python -m json.tool | pygmentize -l json
```
