### ISSUE TITLE
Remove charset from Content-Type on JSON MIME-type

### ISSUE THREAD

**Issue by sborrazas** [jakubroztocil/httpie#264]
According to the IETF RFC, the charset parameter on the JSON MIME type is not a required or an optional parameter. The `charset=utf-8` should be removed from the JSON MIME type.

Reference: http://www.ietf.org/rfc/rfc4627.txt

**Comment by jakubroztocil** [comment]
This has been fixed in [0.9.2](https://github.com/jakubroztocil/httpie/blob/master/CHANGELOG.rst#092-2015-02-24) (forgot to close this).
