### ISSUE TITLE
http doesnt work when running cron jobs

### ISSUE THREAD

**Issue by bkt** [jakubroztocil/httpie#290]
I have a cron job with "http -d "URL" and it doesnt work. however script works fine when executing manually.

how to fix it?

**Comment by gurisko** [comment]
@bkt Let us know if it works so we can close the ticket.

**Comment by bkt** [comment]
This doesent fix the issue, I managed to get it working: "cron-ing" a script which calls another script with http command inside

**Comment by kontrafiktion** [comment]
@bkt do you have a mail server installed? The message

    No MTA installed, discarding output

indicates that there is no mail server (i.e. a mail transfer agent).

Does a cron job work that simply does an

    echo "hello"

And: `cron` has a very reduced environment: is `http` on the path?

just add a cron entry that does:

    * * * * * which http > /tmp/cron-which-http.log 2>&1

and then check `/tmp/cron-which-http.log` after a minute

**Comment by Eleskovic** [comment]
> You will probably have to use `http --ignore-stdin […]`:
> 
> https://httpie.org/doc#scripting

this worked on me. thank you so much!
