### ISSUE TITLE
https://pypi.python.org/pypi/httpie missing file

### ISSUE THREAD

**Issue by papachoco** [jakubroztocil/httpie#301]
There is a new release (0.9.1)  but it's missing from https://pypi.python.org/pypi/httpie.

Thanks

Carlos

**Comment by jakubroztocil** [comment]
@papachoco what happens when you run `pip install -U httpie`? Also, what OS are you on?

**Comment by papachoco** [comment]
IT does work w/ pip, but it does not with easy_install and fails to download the egg using zc.buildout.

I am running MacOS yosemite ..

It does process Downloading httpie-0.9.1-py2.py3-none-any.whl (70kB)

**Comment by papachoco** [comment]
I should mention I am running python 2.7.6

**Comment by papachoco** [comment]
(nti.dataserver)hnic:site-packages csanchez$ easy_install-2.7 -U httpie
/Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'nti.deploymenttools (0.0.dev-r0)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Searching for httpie
Reading https://pypi.python.org/simple/httpie/
/Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'httpie (0.9.1.macosx-10.10-x86-64)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'httpie-0.9.1.macosx (10.10-x86-64)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
/Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/setuptools-12.0.5-py2.7.egg/pkg_resources/__init__.py:2510: PEP440Warning: 'httpie-0.9.1.macosx-10.10 (x86-64)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
Best match: httpie 0.9.0
Downloading https://pypi.python.org/packages/source/h/httpie/httpie-0.9.0.tar.gz#md5=22ecf24e4126fd080f799d95a7ca3037
Processing httpie-0.9.0.tar.gz
Writing /var/folders/jd/g7fjfbn57695542zy0j_84b40000gn/T/easy_install-mUCn_H/httpie-0.9.0/setup.cfg
Running httpie-0.9.0/setup.py -q bdist_egg --dist-dir /var/folders/jd/g7fjfbn57695542zy0j_84b40000gn/T/easy_install-mUCn_H/httpie-0.9.0/egg-dist-tmp-dX_fT4
zip_safe flag not set; analyzing archive contents...
Copying httpie-0.9.0-py2.7.egg to /Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages
Adding httpie 0.9.0 to easy-install.pth file
Installing http script to /Users/csanchez/VirtualEnvs/nti.dataserver/bin

Installed /Users/csanchez/VirtualEnvs/nti.dataserver/lib/python2.7/site-packages/httpie-0.9.0-py2.7.egg
Processing dependencies for httpie
Finished processing dependencies for httpie
(nti.dataserver)hnic:site-packages csanchez$

**Comment by jakubroztocil** [comment]
Interesting, I'm on Python 2.7.9 and `easy_install` gives me this error:

```bash
$ easy_install httpie
Searching for httpie
Reading https://pypi.python.org/simple/httpie/
Best match: httpie 0.9.1.macosx-10.10-x86-64
Downloading https://pypi.python.org/packages/any/h/httpie/httpie-0.9.1.macosx-10.10-x86_64.tar.gz#md5=634a63b1ee02b9240828a218446c216e
Processing httpie-0.9.1.macosx-10.10-x86_64.tar.gz
error: Couldn't find a setup script in /var/folders/xp/4htnd0pj23b5stzrfy966k9m0000gn/T/easy_install-FD8h74/httpie-0.9.1.macosx-10.10-x86_64.tar.gz
```

Tried to update `setuptools`:

```bash
$ pip install -U setuptools
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.4/s/setuptools/setuptools-12.0.5-py2.py3-none-any.whl#md5=87647eb8380c5da10e63fdd7274d8b49
  Downloading setuptools-12.0.5-py2.py3-none-any.whl (502kB): 502kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 3.6
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed setuptools
Cleaning up...
```

And now httpie gets installed:
```bash
$ easy_install httpie
Searching for httpie
Reading https://pypi.python.org/simple/httpie/
/Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'httpie (0.9.1.macosx-10.10-x86-64)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'httpie-0.9.1.macosx (10.10-x86-64)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
/Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/pkg_resources/__init__.py:2510: PEP440Warning: 'httpie-0.9.1.macosx-10.10 (x86-64)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
  PEP440Warning,
Best match: httpie 0.9.0
Downloading https://pypi.python.org/packages/source/h/httpie/httpie-0.9.0.tar.gz#md5=22ecf24e4126fd080f799d95a7ca3037
Processing httpie-0.9.0.tar.gz
Writing /var/folders/xp/4htnd0pj23b5stzrfy966k9m0000gn/T/easy_install-sVYduA/httpie-0.9.0/setup.cfg
Running httpie-0.9.0/setup.py -q bdist_egg --dist-dir /var/folders/xp/4htnd0pj23b5stzrfy966k9m0000gn/T/easy_install-sVYduA/httpie-0.9.0/egg-dist-tmp-BJ_V_A
zip_safe flag not set; analyzing archive contents...
Copying httpie-0.9.0-py2.7.egg to /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages
Adding httpie 0.9.0 to easy-install.pth file
Installing http script to /Users/jakub/.virtualenvs/test-installing-httpie/bin

Installed /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/httpie-0.9.0-py2.7.egg
Processing dependencies for httpie
Searching for Pygments>=1.5
Reading https://pypi.python.org/simple/Pygments/
Best match: Pygments 2.0.2
Downloading https://pypi.python.org/packages/source/P/Pygments/Pygments-2.0.2.tar.gz#md5=238587a1370d62405edabd0794b3ec4a
Processing Pygments-2.0.2.tar.gz
Writing /var/folders/xp/4htnd0pj23b5stzrfy966k9m0000gn/T/easy_install-4UtTmH/Pygments-2.0.2/setup.cfg
Running Pygments-2.0.2/setup.py -q bdist_egg --dist-dir /var/folders/xp/4htnd0pj23b5stzrfy966k9m0000gn/T/easy_install-4UtTmH/Pygments-2.0.2/egg-dist-tmp-rYqUgX
creating /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/Pygments-2.0.2-py2.7.egg
Extracting Pygments-2.0.2-py2.7.egg to /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages
Adding Pygments 2.0.2 to easy-install.pth file
Installing pygmentize script to /Users/jakub/.virtualenvs/test-installing-httpie/bin

Installed /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/Pygments-2.0.2-py2.7.egg
Searching for requests>=2.3.0
Reading https://pypi.python.org/simple/requests/
Best match: requests 2.5.1
Downloading https://pypi.python.org/packages/source/r/requests/requests-2.5.1.tar.gz#md5=c270eb5551a02e8ab7a4cbb83e22af2e
Processing requests-2.5.1.tar.gz
Writing /var/folders/xp/4htnd0pj23b5stzrfy966k9m0000gn/T/easy_install-uvhHU3/requests-2.5.1/setup.cfg
Running requests-2.5.1/setup.py -q bdist_egg --dist-dir /var/folders/xp/4htnd0pj23b5stzrfy966k9m0000gn/T/easy_install-uvhHU3/requests-2.5.1/egg-dist-tmp-QxG41c
creating /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg
Extracting requests-2.5.1-py2.7.egg to /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages
Adding requests 2.5.1 to easy-install.pth file

Installed /Users/jakub/.virtualenvs/test-installing-httpie/lib/python2.7/site-packages/requests-2.5.1-py2.7.egg
Finished processing dependencies for httpie
```

But it's not the latest version: 

```bash
$ http --version
0.9.0
```

**Comment by jakubroztocil** [comment]
Fixed. I accidentally did `python setup.py bdist upload` instead of `sdist` when releasing `0.9.1`.

(Pip now defaults to the `wheel` package, that is also available, that's why it only failed with `easy_install`.)

Thanks for the report :cake:

**Comment by papachoco** [comment]
Great thanks a lot
