### ISSUE TITLE
POST a JSON entity

### ISSUE THREAD

**Issue by cmoulliard** [jakubroztocil/httpie#307]
Is it possible to post such a json query containing an entity ?

http POST host.org customer:='id=222 name=charles'

JSON

````
{"Customer ":{"id":"222","name":"charles"}}
````

**Comment by jakubroztocil** [comment]
It is possible to embed the nested object as raw JSON:

```bash
$ http host.org customer:='{"id":222, "name": "charles"}'
```

Or the whole raw payload can be passed in via `stdin`, which is often easier:

```bash
$ echo '{"Customer ":{"id":"222","name":"charles"}}' | http host.org
```

**Comment by cmoulliard** [comment]
Thx for the trick
