### ISSUE TITLE
Own colorprofile for "dark backgrounds"

### ISSUE THREAD

**Issue by d0x** [jakubroztocil/httpie#322]
The attached images shows that dark blue for integer values isn't readable.

![image](https://cloud.githubusercontent.com/assets/2202723/6576959/e24bd62c-c73a-11e4-89f3-70e125310528.png)

I used iTerm 2 with the dark profile.

Thanks a lot.

**Comment by jakubroztocil** [comment]
Do you specify a `--style` or it's the default one? What version of HTTPie do you use?

**Comment by d0x** [comment]
I haven't set any `--style`s. This Version:

```
http --version
0.9.2
```

I installed it over homebrew

**Comment by jakubroztocil** [comment]
Strange, the default scheme in `0.9.2` is Solarized which look nothing like what the screenshot shows. 

This is what it looks like for me when I choose `Load Presets… > Dark Background`:


![screen shot 2015-03-11 at 15 17 24](https://cloud.githubusercontent.com/assets/326885/6598137/dbbda9ee-c801-11e4-80c9-d4b3c8d242bb.png)

**Comment by d0x** [comment]
I checked the `~/.httpie/config.json` which looks like this:

```
{
    "__meta__": {
        "about": "HTTPie configuration file",
        "help": "https://github.com/jkbr/httpie#config",
        "httpie": "0.8.0"
    },
    "default_options": [],
    "implicit_content_type": "json"
}
```

**Comment by jakubroztocil** [comment]
I'm still not sure what causes the problem with the default style. But please have a look at the output of `http --help`. There you'll find a list of all the supported styles which you can experiment with. Once you find one you like, add it to your config file as `"default_options": ['--style=<STYLE>']`.

**Comment by d0x** [comment]
Hm, maybe my terminal is the problem?

![image](https://cloud.githubusercontent.com/assets/2202723/6732496/898b1386-ce4c-11e4-84e3-a1d4020c9bfb.png)

I'm using iTerm with fish.

**Comment by d0x** [comment]
Yes, with the default osx terminal it works.
But not with `iTerm2`

**Comment by jakubroztocil** [comment]
@d0x what do you get when you run this in iTerm2? 

```bash
echo $TERM
```

**Comment by d0x** [comment]
```
~ echo $TERM
xterm
```

**Comment by jakubroztocil** [comment]
Okay, I think that's the problem — HTTPie things your terminal only supports 8 colors.

Setting your `$TERM` to `xterm-256color` should fix that. You can quickly verify if it's the case by running:

```bash
$ TERM=xterm-256color http --style=xcode httpbin.org/post count:=2131
```
If it looks good, add `export TERM=xterm-256color` to you shell initialization file (e.g. `~/.bash_profile`).

**Comment by d0x** [comment]
+1. Thank you. Works great.
