### ISSUE TITLE
Following Link header

### ISSUE THREAD

**Issue by raine** [jakubroztocil/httpie#323]
I don't know if it's in the scope of this project but I'm wondering if there's a way to make httpie follow URLs in the `Link` header for certain amount of responses.

Bugsnag has an API where the next page of results is in the `Link` header like this:

    Link: <https://api.bugsnag.com/errors/550b030f1e5e3784a862dcf6/events?direction=desc&offset=550b0377dcf11de8071b5b73&per_page=100&sort=received_at>; rel="next"

I'm looking for a way to get multiple pages of results without writing a lot of code unnecessarily.

Thanks.

**Comment by jakubroztocil** [comment]
I'm afraid that interpreting these headers in any ways is outside of the scope of this project. What is your use case?

**Comment by raine** [comment]
I want to get more than one page of data from the API and pipe it to `jq` for further processing.

**Comment by jakubroztocil** [comment]
This sounds like a job for a custom script. 

It would be fairly easy to implement with Python Requests, for example, as it has support for `Link` headers: http://docs.python-requests.org/en/latest/user/advanced/#link-headers

**Comment by raine** [comment]
Cheers.
