### ISSUE TITLE
How to do recursive downloads?

### ISSUE THREAD

**Issue by Immortalin** [jakubroztocil/httpie#324]
Hi, how do you do recursive downloads similar to [this](http://www.gnu.org/software/wget/manual/html_node/Recursive-Download.html#Recursive-Download).

**Comment by jakubroztocil** [comment]
Recursive downloads is a feature that is beyond the scope of a simple HTTP client that HTTPie tries to be I'm afraid. But `wget -r` does a great job and there are other specialised tools such as [HTTrack](https://www.httrack.com/) that are good at that.
