### ISSUE TITLE
Escaping colons in key name

### ISSUE THREAD

**Issue by Vadi** [jakubroztocil/httpie#327]
My FORM post needs to have key/value pairs like this --

    person:FirstName=GILDERMAN

I tried with

    person\:FirstName=GILDERMAN

The escaping char doesn't seems to be working. In this case, the key value just gets added to HEADERS.

**Comment by jakubroztocil** [comment]
If you write it like that, the `\` gets eaten by the shell. Using a double `\\` or wrapping the string in single quotes will do the trick:

```bash
$ http httpbin.org/post 'person\:FirstName=GILDERMAN'
```
