### ISSUE TITLE
X-API-Token

### ISSUE THREAD

**Issue by MateuszG** [jakubroztocil/httpie#328]
curl -v -H "Authorization: Token 22ca637f0f1861b3f9b13eb30a080c603d87ed4d" 0.0.0.0:8888/

What is the equivalent in httpie?

Tried without success:
 http GET 0.0.0.0:8888 X-API-Token:f37305505bf1fa236ba451bfc3b2c5324ea76c6a

**Comment by jakubroztocil** [comment]
```bash
$ http -v :8888  'Authorization: Token 22ca637f0f1861b3f9b13eb30a080c603d87ed4d'
```
