### ISSUE TITLE
More permissive Content-Type interpretation to pretty-print responses

### ISSUE THREAD

**Issue by p2** [jakubroztocil/httpie#334]
It looks like HTTPie doesn't like FHIR's content type of `application/json+fhir` and therefore doesn't pretty-print the response. It would be neat if it did! Issue #92 is related but here the content type could be enough for HTTPie to figure out how to pretty print, no need to force from the user side.

Example:

```sh
http -j http://argonaut.healthintersections.com.au/open/OperationDefinition/fso-document
```

**Comment by jakubroztocil** [comment]
@p2 I think you might be using an older version of HTTPie — it's correctly interpreted as JSON in the latest version.

```bash
$ http --version
0.9.2
```

**Comment by p2** [comment]
Oh, I've updated via brew but only have 0.8.0. Happy to hear that it's supposed to be working, thanks!
