### ISSUE TITLE
Does not respond to CTRL-C when website fails to respond.

### ISSUE THREAD

**Issue by withnale** [jakubroztocil/httpie#341]
HTTPie will wait for a respond until the timeout is reached but during this period it cannot be interrupted using CTRL-C.

**Comment by jakubroztocil** [comment]
I'm unable to reproduce it:

```bash
$ time http httpbin.org/delay/10
^C

real	0m0.958s
user	0m0.123s
sys	0m0.053s
```

What system are you on?
