### ISSUE TITLE
Interactive Shell

### ISSUE THREAD

**Issue by uppfinnarn** [jakubroztocil/httpie#343]
I think it would be useful to have a simple, readline-based interactive shell for interacting with e.g. an API. Instead of having to type something along the lines of:

```
http GET something.com/api/v1/things Authorization:"Bearer abcdef12345"
```

You could do something more like:

```
http -i something.com
>> Authorization: Bearer abcdef12345
>> GET /api/v1/things
```

This would save people a lot of typing when interacting with something where the same headers, parameters, etc. are passed over and over - such as when developing or testing an API.

Sessions could optionally be persisted in the shell as well, and discarded on exit.

**Comment by jakubroztocil** [comment]
I've been playing with this idea myself for a while. It's not something that should come anytime soon though. In the meantime, you can check out [repl](https://github.com/defunkt/repl).

**Comment by eliangcs** [comment]
Although this issue is already older than a year, but I just wrote a tool that just fits your need. Check it out: https://github.com/eliangcs/http-prompt

**Comment by Oxicode** [comment]
+1 jkbrzt

**Comment by jkbrzt** [comment]
@eliangcs `http-prompt` looks pretty awesome, thanks 👍😃
