### ISSUE TITLE
How does one upload a picture using httpie ?

### ISSUE THREAD

**Issue by allan-simon** [jakubroztocil/httpie#348]
the example in the doc only use a txt file, but if you try with a binary format (an image for example it complains ) 

```
http --form POST localhost:7777 avatar=@valid_avatar.jpg
```

**Comment by jakubroztocil** [comment]
Form file fields use `@` as the key-value separator (`=@` is for contents embedding text and JSON files):

```bash
$ http --form :7777 avatar@valid_avatar.jpg
```

Docs:

* [Request Items](https://github.com/jakubroztocil/httpie#request-items)
* [File Upload Forms](https://github.com/jakubroztocil/httpie#file-upload-forms)
