### ISSUE TITLE
ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by matiaskorhonen** [jakubroztocil/httpie#351]
I've having some issues trying to use HTTPie with <https://matiaskorhonen.fi>, which is confusing since the site work fine in every browser I've tried and with curl. HTTPie on the other hand gives a `Connection reset by peer` error:

```console
~ » curl -I https://matiaskorhonen.fi
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 06 May 2015 18:41:13 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 7417
Connection: keep-alive
Last-Modified: Tue, 05 May 2015 19:25:22 GMT
Vary: Accept-Encoding
Alternate-Protocol: 443:npn-spdy/2

~ » http --verbose HEAD https://matiaskorhonen.fi

http: error: ConnectionError: ('Connection aborted.', error(54, 'Connection reset by peer'))
~ » http --version
0.9.2
~ »
```

Using `--verify=no` doesn't help either. The server uses SNI TLS, might that be the issue?

**Comment by jakubroztocil** [comment]
Yes, this seems to be related to SNI. You can either upgrade to Python 2.7.9 or 3.4, or manually install some dependencies, if you are stuck with an older version: https://github.com/jakubroztocil/httpie#sni-server-name-indication

```bash
$ python --version
Python 2.7.9
```

```bash
$ http --verify=no --verbose HEAD https://matiaskorhonen.fi
```
```http
HEAD / HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: matiaskorhonen.fi
User-Agent: HTTPie/1.0.0-dev
```

```http
HTTP/1.1 200 OK
Alternate-Protocol: 443:npn-spdy/2
Connection: keep-alive
Content-Encoding: gzip
Content-Type: text/html; charset=utf-8
Date: Wed, 06 May 2015 21:17:32 GMT
Last-Modified: Tue, 05 May 2015 19:25:22 GMT
Server: nginx
Vary: Accept-Encoding
```

**Comment by matiaskorhonen** [comment]
I got it to work with Python 3.

Cheers.

**Comment by kyteague** [comment]
I get this issue as well, using python 2.7.11 under OSX.  I tried both pip and brew versions.

The equivalent curl command has no issue.

httpie version 0.9.3

**Comment by jkbrzt** [comment]
@kyteague is it a public URL?

**Comment by kyteague** [comment]
@jkbrzt no, unfortunately it's a private API.

**Comment by jkbrzt** [comment]
@kyteague Not sure what the issue is yet, but I'm only able to reproduce it on Python 2.7.10. It works fine on Python 2.7.11. I think you're on Python 2.7.10, too.

**Comment by kyteague** [comment]
I found the issue.

The `http` script hardcodes `#!/usr/bin/python` instead of the canonical `#!/usr/bin/env python`

This caused python 2.7.10 (from OSX) to be used instead of 2.7.11 (my default python from brew).  This should definitely be patched as the latter more accurately describes the system python executable.

**Comment by jkbrzt** [comment]
@kyteague Yeah, the formula currently uses the system Python 2.7 which has some issues.  I'm now testing a [Python3-based formula](https://gist.github.com/jkbrzt/e59a0cde6ae6f59f2182) which I'm considering for the next release to avoid issues like that. Feel free to give it a try:

brew install https://gist.githubusercontent.com/jkbrzt/e59a0cde6ae6f59f2182/raw/d745c6b79677f4a72e27fa67d6a4f57f4b11911d/httpie.rb

``

**Comment by tunix** [comment]
@jkbrzt works as expected! thanks!

**Comment by janhenriko** [comment]
Installed [httpie-ntlm](https://github.com/httpie/httpie-ntlm) with Python3, and that worked (on my MacOSX)

`sudo python3 setup.py install`

**Comment by duginivijay** [comment]
@jakubroztocil  I tried the one you suggested but it has thrown the below error.
VJ:audit vijay.dugini$ brew install https://gist.githubusercontent.com/jkbrzt/e59a0cde6ae6f59f2182/raw/httpie.rb

curl: (22) The requested URL returned error: 404 Not Found
Error: Failure while executing: /usr/bin/curl --show-error --user-agent Homebrew/1.3.2\ (Macintosh;\ Intel\ Mac\ OS\ X\ 10.12.6)\ curl/7.54.0 --fail --progress-bar --location --remote-time --continue-at - --output /Users/vijay.dugini/Library/Caches/Homebrew/Formula/httpie.rb https://gist.githubusercontent.com/jkbrzt/e59a0cde6ae6f59f2182/raw/httpie.rb

**Comment by jakubroztocil** [comment]
@duginivijay the Python 3 based formula is available directly from Homebrew (`brew install httpie`).

**Comment by duginivijay** [comment]
Ignore my post mate. I had multiple version of pythons in my machine due to which it wasn't able to pick the right one and was throwing error. Posting this thinking it may be helpful for someone.
