### ISSUE TITLE
not support to post a simple string.

### ISSUE THREAD

**Issue by hackrole** [jakubroztocil/httpie#352]
I write a simple node for learning. I would to post a request like below
```
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 13
Content-Type: plain/text
Host: localhost:8000
User-Agent: HTTPie/0.9.1

buy node in action
```
but seems the lib not support such thing. I have to use --form or --json, which was not my willing.

**Comment by jakubroztocil** [comment]
```bash
echo 'buy node in action' | http …
```

See: https://github.com/jakubroztocil/httpie#redirected-input

**Comment by hackrole** [comment]
that's it. thanks.
