### ISSUE TITLE
ConnectionRefused

### ISSUE THREAD

**Issue by qasimalbaqali** [jakubroztocil/httpie#353]
So I am testing my web service with HTTpie and I am trying to issue a GET request with the following 

```python 
http --json --auth <ADMIN_EMAIL>:<PASSWORD> GET http://127.0.0.1:5000/api/v1.0/posts
```

```python
@api.route('/posts/')
def get_posts():
    page = request.args.get('page', 1, type=int)
    pagination = Post.query.paginate(
        page, per_page=current_app.config['POSTS_PER_PAGE'],
        error_out=False)
    posts = pagination.items
    prev = None
    if pagination.has_prev:
        prev = url_for('api.get_posts', page=page-1, _external=True)
    next = None
    if pagination.has_next:
        next = url_for('api.get_posts', page=page+1, _external=True)
    return jsonify({
        'posts': [post.to_json() for post in posts],
        'prev': prev,
        'next': next,
        'count': pagination.total
    })
```
api is a blueprint

And I am getting the following error
```pythonhttp: error: ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))```
When visiting ```http://127.0.0.1:5000/api/v1.0/posts``` in the browser it works just fine I can see all the json.
Tried to google around but nothing came up about HTTpie in exact or anything related to flask.

**Comment by jakubroztocil** [comment]
I'd look at the output of the running Flask app to see if there is something useful there.

**Comment by stijnblommerde** [comment]
Start the server in a separate terminal window (if you have forgotten)
