### ISSUE TITLE
Is possible send raw post payload

### ISSUE THREAD

**Issue by a-x-** [jakubroztocil/httpie#356]
... w/o escaping and another magic

Is it really?

Under option like `--raw-payload`

**Comment by jakubroztocil** [comment]
Yes, any data passed in via `STDIN` will be sent as the request body, e.g.: 

```bash
$ echo 'raw payload' | http httpbin.org/post
```

https://github.com/jakubroztocil/httpie#redirected-input

**Comment by a-x-** [comment]
Thank you, Jakub!

**Comment by mrcoles** [comment]
Other than `--ignore-stdin` I don’t see any mention of this inside `http --help`, might it be a good addition to the help text?

**Comment by henrik242** [comment]
You can also use `http httpbin.org/post <<< 'raw payload'`

**Comment by furkanmustafa** [comment]
But, 

```
$ echo 'running' | http -v put localhost:5000/state
```

is sending `Content-Type: application/json` header.

```
PUT /state HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 8
Content-Type: application/json
Host: localhost:5000
User-Agent: HTTPie/0.9.9

running
```

and a proper implementation on the receiving end is of course trying to parse that as a JSON, and failing.

**Comment by vlcinsky** [comment]
@furkanmustafa `application/json` is default content-type used by `httpie`.

If you explicitly state the content type in your request, it will be resolved:
```bash
$ echo 'running' |http httpbin.org/post Content-Type:text/plain
```
or even with sending compressed content:
```bash
$ echo 'running' |gzip |http httpbin.org/post Content-Type:text/plain Content-Encoding:gzip
```

**Comment by WeihanLi** [comment]
> You can also use `http httpbin.org/post <<< 'raw payload'`

seemed not working with powershell,  ` 'rawBody' | http post :8080/api/events` worked for me
