### ISSUE TITLE
Using HTTPIE with GNU Parallel

### ISSUE THREAD

**Issue by CMCDragonkai** [jakubroztocil/httpie#359]
This works:

```
seq 1 | parallel -n0 "curl -H 'Content-Type: application/json' http://httpbin.org/post -X POST -d '{\"url\":\"http://google.com/\"}'"
```

But this doesn't:

```
seq 1 | parallel -n0 "http POST http://httpbin.org/post url=http://google.com/"
```

The result is:

```
http: error: Request body (from stdin or a file) and request data (key=value) cannot be mixed.
```

It seems that by using a pipe with parallel, httpie is thinking that it's meant to take data from stdin/file, and won't take in the command like request data.

The `-n0` command makes parallel not pass any parameters to the command.

**Comment by jakubroztocil** [comment]
You can use `--ignore-stdin` to tell HTTPie to not read from standard input even though it's redirected:

```bash
$ seq 1 | parallel -n0 "http --ignore-stdin httpbin.org/post url=http://google.com/"
```

More details: https://github.com/jakubroztocil/httpie#redirected-input
