### ISSUE TITLE
Invalid Syntax: help="""

### ISSUE THREAD

**Issue by synedra** [jakubroztocil/httpie#363]
I'm trying to use httpie with my own custom authentication.  I only need a 'section' for auth (the rest comes from a user configuration file'

```
sjc-mpl23:httpie khunter$ http --auth-type=edgegrid --auth=default '/api/v1/diagnostic-tools/locations'
Traceback (most recent call last):
  File "/usr/local/bin/http", line 9, in <module>
    load_entry_point('httpie==1.0.0-dev', 'console_scripts', 'http')()
  File "build/bdist.macosx-10.10-intel/egg/httpie/core.py", line 79, in main
  File "/Users/khunter/Library/Python/2.7/lib/python/site-packages/httpie-1.0.0_dev-py2.7.egg/httpie/cli.py", line 399
    help="""
       ^
SyntaxError: invalid syntax
```

My auth is as follows:

```
sjc-mpl23:httpie_edgegrid khunter$ more httpie_edgegrid.py 
```

```python
"""
NTLM auth plugin for HTTPie.

"""
from httpie.plugins import AuthPlugin
from akamai.edgegrid import EdgeGridAuth
import ConfigParser,os,sys
__version__ = '1.0.0'
__author__ = 'Kirsten Hunter'
__licence__ = 'Apache 2.0'


class EdgeGridAuthPlugin(AuthPlugin):

    name = 'EdgeGrid auth'
    auth_type = 'edgegrid'
    description = ''

    def get_auth(self, section):
        config = ConfigParser.ConfigParser()
        config.readfp(open('~/.edgerc'))
        if not config.has_section(section):
                        err_msg = "ERROR: No section named %s was found in your %s file\n" % (configuration, arguments["config_file"])
                        err_msg += "ERROR: Please generate credentials for the script functionality\n"
                        err_msg += "ERROR: and run 'python gen_edgerc.py %s' to generate the credential file\n" % configuration
                        sys.exit( err_msg )
        for key, value in config.items(section):
                arguments[key] = value  
        auth = EdgeGridAuth(
            client_token=config.client_token,
            client_secret=config.client_secret,
            access_token=config.access_token
        )
        return auth
```

**Comment by sigmavirus24** [comment]
How did you install httpie?

**Comment by synedra** [comment]
sudo python setup.py install

**Comment by synedra** [comment]
And installing with pip gives the same:

sudo pip install httpie
Requirement already satisfied (use --upgrade to upgrade): httpie in /Users/khunter/Library/Python/2.7/lib/python/site-packages/httpie-1.0.0_dev-py2.7.egg
Requirement already satisfied (use --upgrade to upgrade): requests>=2.3.0 in /Library/Python/2.7/site-packages/requests-2.4.1-py2.7.egg (from httpie)
Requirement already satisfied (use --upgrade to upgrade): Pygments>=1.5 in /Library/Python/2.7/site-packages/Pygments-2.0.2-py2.7.egg (from httpie)
Cleaning up...
sjc-mpl23:httpie khunter$

**Comment by sigmavirus24** [comment]
Yeah, I'm just confused because [this line][] doesn't match up with your traceback. Could you paste about 10 lines of context around L399 in `httpie/cli.py` in your local copy?

[this line]: https://github.com/jakubroztocil/httpie/blob/d8b819b03f29111c7e4ba496988e7abf58636986/httpie/cli.py#L399

**Comment by synedra** [comment]
It's in this block, the 399 is where the help line is...

_auth_plugins = plugin_manager.get_auth_plugins()
auth.add_argument(
    '--auth-type',
    choices=[plugin.auth_type for plugin in _auth_plugins],
    default=_auth_plugins[0].auth_type,
    help="""
    The authentication mechanism to be used. Defaults to "{default}".

    {types}

    """
    .format(default=_auth_plugins[0].auth_type, types='\n    '.join(
        '"{type}": {name}{package}{description}'.format(
            type=plugin.auth_type,
            name=plugin.name,
            package=(
                '' if issubclass(plugin, BuiltinAuthPlugin)
                else ' (provided by %s)' % plugin.package_name
            ),

**Comment by synedra** [comment]
I reinstalled and all seems ok now.
