### ISSUE TITLE
Overriding auth plugin help

### ISSUE THREAD

**Issue by synedra** [jakubroztocil/httpie#365]
I have an authentication scheme that I need to implement.  I'd like to be able to use the standard setup, but here are the issues with that:
* I only want to pass a single parameter to the plugin (section) not username:password.  I don't want it to prompt for a password.
* I need to be able to set the Host header within the plugin.
* Credentials and hostnames will be set based on the section from a configuration file on the host.

Is there a way to do the first two things within an authentication plugin?  I can figure out how to hijack the system to make it work, but would rather do it in a plugin directly.

**Comment by jakubroztocil** [comment]
1. Unfortunately, the API was originally made for username/password pairs, but you can pass just an empty password for now: `--auth username:` 
2. Your plugin [returns a `requests.auth.AuthBase` subclass](https://github.com/jakubroztocil/httpie/blob/d8b819b03f29111c7e4ba496988e7abf58636986/httpie/plugins/base.py), and there you have access the request object on which you can [set headers](https://github.com/kennethreitz/requests/blob/f5dacf84468ab7e0631cc61a3f1431a32e3e143c/requests/auth.py#L50).

**Comment by synedra** [comment]
I'm not sure how I would do that in the plugin.  I don't see any examples where the request sets things within the plugin.  Here's what I have:

"""
Edgegrid auth plugin for HTTPie.

"""
from httpie.plugins import AuthPlugin
from akamai.edgegrid import EdgeGridAuth

__version__ = '1.0.0'
__author__ = 'Kirsten Hunter'
__licence__ = 'Apache 2.0'


class EdgeGridAuthPlugin(AuthPlugin):

    name = 'EdgeGrid auth'
    auth_type = 'edgegrid'
    description = ''

    def get_auth(self,username,password):
	return EdgeGridAuth(
            client_token='xxx',
            client_secret='xxx',
            access_token='xxx'
	)

**Comment by jakubroztocil** [comment]
I'd extend `EdgeGridAuth`:

```python
"""
Edgegrid auth plugin for HTTPie.

"""
from httpie.plugins import AuthPlugin
from akamai.edgegrid import EdgeGridAuth

__version__ = '1.0.0'
__author__ = 'Kirsten Hunter'
__licence__ = 'Apache 2.0'


class MyEdgeGridAuth(EdgeGridAuth):
    
    def __call__(self, r):
        r = super(MyEdgeGridAuth, self).__call__()
        r.headers['My-Header'] = 'value'
        return r


class EdgeGridAuthPlugin(AuthPlugin):

    name = 'EdgeGrid auth'
    auth_type = 'edgegrid'
    description = ''

    def get_auth(self,username,password):
    return MyEdgeGridAuth(
            client_token='xxx',
            client_secret='xxx',
            access_token='xxx'
    )
```

**Comment by synedra** [comment]
That gets me 90% of the way there - the only remaining problem is that I won't know the URL until I do the get_auth piece, but I'll try with some global variables and see what I can do.

Thanks so much for the help!!

**Comment by jakubroztocil** [comment]
Good luck with it :+1: Btw, it should be possible even without global variables.
