### ISSUE TITLE
Newer release broke auth_type edge grid

### ISSUE THREAD

**Issue by synedra** [jakubroztocil/httpie#439]
Hello,

I’ve been encouraging my customers to use HTTPie instead of Curl for interfacing with our APIs - however in order to make the plugin work well I had to override the :/ setup for localhost to use it for the host in the configuration file.  It was working fine with httpie 0.7.0 but has since been broken by your more recent changes.  Would it be possible for you to take a look and see what changed to make this stop working?

```
def get_auth(self, username, password):
    home = os.environ['HOME']   
    rc = EdgeRc("%s/.edgerc" % home) 

    if not rc.has_section(username):
        err_msg = "\nERROR: No section named '%s' was found in your .edgerc file\n" % username
        err_msg += "ERROR: Please generate credentials for the script functionality\n"
        err_msg += "ERROR: and run 'python gen_edgerc.py %s' to generate the credential file\n"
        sys.stderr.write(err_msg)
        sys.exit(1)

    host=rc.get(username, 'host')
    host=host.replace("https://", "")
    host= host.replace ("/","")
    host += "/"
    auth = HTTPieEdgeGridAuth(
        hostname = host,
        client_token=rc.get(username, 'client_token'),
        client_secret=rc.get(username, 'client_secret'),
        access_token=rc.get(username, 'access_token'),
        max_body=rc.getint(username, 'max_body')
    )
    return auth
```

**Comment by sigmavirus24** [comment]
I wonder if this project should start using [Bountysource](https://www.bountysource.com/) so corporate interests with bugs (like this one) can sponsor the work to fix the bugs that affect them.
