### ISSUE TITLE
httpie doesn't work in msysgit

### ISSUE THREAD

**Issue by ctian1** [jakubroztocil/httpie#445]
after running an httpie command apart from --help or --debug, nothing appears but httpie doesn't stop executing either (there's just a blinking cursor, doesn't return to normal command prompt). httpie works normally in windows command prompt though.

HTTPie 0.9.3
HTTPie data: C:\Users\me\AppData\Roaming\httpie
Requests 2.9.1
Pygments 2.1.3
Python 3.4.1 (v3.4.1:c0e311e010fc, May 18 2014, 10:45:13) [MSC v.1600 64 bit (AMD64)] win32

MINGW32_NT-10.0-WOW

**Comment by jkbrzt** [comment]
Can you try to run it with ``--ignore-stdin`` and see if that works?

```
http --ignore-stdin httpie.org
```

**Comment by pangeacake** [comment]
That worked! o.o

**Comment by jkbrzt** [comment]
Cool. I was going to submit an issue to the msysGit repo but then I read that's it's not supported any longer:

> msysGit has been superseded by Git for Windows 2.x https://git-for-windows.github.io/

**Comment by pangeacake** [comment]
I believe I actually am using "Git for Windows", it's packaged with it or something.

**Comment by djgraff209** [comment]
This impacts msys2 implementation, which is what git for windows is based on I believe

Using --ignore-stdin mitigates the hold up but is not ideal.

**Comment by jkbrzt** [comment]
Related: https://github.com/git-for-windows/git/issues/778

**Comment by jakubroztocil** [comment]
#828
