### ISSUE TITLE
Feature request: support S3 authentication

### ISSUE THREAD

**Issue by jamshid** [jakubroztocil/httpie#479]
It would be great if httpie supported S3 authentication. That would make interacting with AWS S3 and S3-compatible servers so much easier than using a crusty S3 client like s3curl.pl (https://aws.amazon.com/code/128).

Hopefully it's easy to use https://github.com/tax/python-requests-aws to add the "Authorization: AWS access-key:hash" and other request headers. 

Being able to handle the different types of endpoints might be tricky:

https://s3.amazonaws.com/mybucket
https://mybucket.s3.amazonaws.com/
https://s3compatible.example.com/mybucket

**Comment by DrJackilD** [comment]
@jamshid @jkbrzt 

I think this must be a plugin, like [httpit-api-auth](https://github.com/pd/httpie-api-auth) plugin. I think I can implement it like separated PyPi packages, or if you, guys, have suggestions, make it as a part of httpie.

I think, usage can be like:
```
http --auth-type=aws-auth --auth='<your-access-key-id>@<date>/<aws-region>/<aws-service>/aws4_request' METHOD aws_endpoint
...
```
Date can be optional argument (e. g. just already put /<aws-region> after @ and plugin will input datetime.datetime.now() in properly format). I see few problems here:
1. Calculate 256-bit signature with algorithm, which provided by Amazon (http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-examples-using-sdks.html). Signature can be calculated with payload or without it. First variant is more secure. But I think this can be added later.
2. POST request use different scheme, which need to add credentials to form (for example, when you upload files to bucket). I don't know for this moment how to implement it in plugin.

Any thoughts?

**Comment by jamshid** [comment]
Thanks @DrJackilD! V4 signatures would be nice, but personally I'm more interested in V2, and that seems to be all that https://github.com/tax/python-requests-aws currently supports (if you want to reuse that). The user should just have to specify the access key, secret, and endpoint.

1. Yes, V4 signatures do get complicated and expensive with payload hashing. There seems to be a lot of options -- unsigned, single, multiple chunks.

2. I personally don't need httpie to handle browser form uploads.

**Comment by DrJackilD** [comment]
@jamshid 

Actually, I have a question: why you don't using [official AWS CLI](https://github.com/aws/aws-cli)? I've found it when look at AWS API documentation. Looks like a great tool and also actively maintained.

**Comment by jamshid** [comment]
@DrJackilD I do use aws-cli and s3cmd and other tools, but httpie is nice because it's raw HTTP. I can add arbitrary query args and headers. This came up because I wanted to test S3's error handling around invalid S3 multipart requests, to compare to an S3-compatible service.

**Comment by jakubroztocil** [comment]
You can use `httpie-aws-auth` for S3 authentication: https://github.com/httpie/httpie-aws-auth
