### ISSUE TITLE
Multiple cookies with attributes

### ISSUE THREAD

**Issue by dufferzafar** [jakubroztocil/httpie#498]
How can I send two cookies each of which has some attributes.

The current syntax uses `;` as a separator for multiple cookies, but that is a bit odd since cookies can have attributes which are separated by `;`.

Using multiple `Cookie` headers doesn't work! :/

```
$ http http://httpbin.org/cookies 'Cookie:doo=dar; Path=/; Max-Age=0' 'Cookie:foo=bar; Path=/; Max-Age=0'

HTTP/1.1 200 OK
Content-Length: 40
Content-Type: application/json
Date: Wed, 03 Aug 2016 11:43:35 GMT

{
    "cookies": {
        "foo": "bar"
    }
}
```

**Comment by jakubroztocil** [comment]
Cookie attributes (like `Path`, `Max-Age`, `HttpOnly`, `Secure`, etc.) are sent by the server in the `Set-Cookie` header. But the `Cookie` header sent by the client doesn't included them; it only contains the `name=value; name2=value2` pairs. 

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cookie
