### ISSUE TITLE
http command not found

### ISSUE THREAD

**Issue by ayushidalmia** [jakubroztocil/httpie#500]
Hi,

I have installed httpie using pip on OS X. However, I am not able to use it. I get the following errorL

```
-bash: http: command not found
```

**Comment by francocorreasosa** [comment]
Please check your `pip` bin directory is on your PATH.

**Comment by type-a-developer** [comment]
I was using a virtual environment (venv) with Python Flask so I had to run the http commands in my venv directory were I installed the HTTPie application using pip.  If you want it available everywhere add it to the global path as suggested by francocorreasosa.

**Comment by ddeveloperr** [comment]
I had the same issue like @ayushidalmia 
```
$  http: command not found
```
  using ubuntu consoole over cloud9 IDE c9.io and after:
 ```
$  sudo pip install --upgrade httpie
```
 This working as expected: 
```
$ http httpie.org
```
```

**Comment by jakubroztocil** [comment]
If you system cannot find the `http` command, make sure the directory where it’s been installed is on your `$PATH`.

**Comment by 8secz-johndpope** [comment]
On Catalina with miniconda installed - and was seeing this running a vanilla 
**npm install httpie -g** 
sudo fixed it.

**Comment by jakubroztocil** [comment]
@8secz-johndpope HTTPie is not a JavaScript project, but a Python one. Please see https://httpie.org/docs#installation for all the available way to install HTTPie.

(The `npm` package named "httpie" is completely unrelated and, sadly, the author refuses to rename it, which generates confusion like this. https://github.com/lukeed/httpie/issues/5)

**Comment by 8secz-johndpope** [comment]
OMG - when I go to the official site - it says
<tool>
<img width="678" alt="Screen Shot 2020-06-15 at 9 25 26 am" src="https://user-images.githubusercontent.com/50567111/84606512-2edc6f00-aeea-11ea-8dea-bd25fda89fc1.png">

maybe consider changing this to pip to avoid this confusion.
and put a big warning - not related to npm install. .....

**Comment by jakubroztocil** [comment]
@8secz-johndpope Some comments:

1. `pip` is not the only tool that can install HTTPie. 2. `npm` is not the only that cannot install HTTPie.  
3. you can see a list of the supported  tools when you click the <tools> link

Thanks for the feedback.
