### ISSUE TITLE
Add 'httpie' as a default entry point alias

### ISSUE THREAD

**Issue by Miserlou** [jakubroztocil/httpie#505]
This might just be me being lazy, but every damn time I try to use this tool, I type `$ httpie blah.com`, then get `-bash: httpie: command not found`, then I `$ pip install httpie` and get `Requirement already satisfied (use --upgrade to upgrade): httpie in /usr/local/lib/python2.7/site-packages`, then I have to go to this page to see that the tool is actually called `http`.

Since the repo is called `httpie`, can you please add `httpie` as an entry point alias in setup.py so that I don't get stuck in this loop any more? It'd be far more symmetrical - installing a package at one name and then executing it another is really annoying.

Just a thought,
R

**Comment by hmeine** [comment]
As I just posted in #506, that's not only a good idea. One could consider a `httpie` frontend that writes usage instructions (pointing to `http` or `https` executables) to stderr and bail out, but maybe that's just cruft.

**Comment by jakubroztocil** [comment]
I actually once briefly added an `httpie` command for managing sessions etc., but it didn’t get included in any release (https://github.com/jakubroztocil/httpie/commit/5cc5b13555f359712e0c5784bebdb091c34e6c82). I’d like to keep the option to add _an_ `httpie` command open for the future. Still thanks for PR, though!
