### ISSUE TITLE
http error 

### ISSUE THREAD

**Issue by cunde** [jakubroztocil/httpie#508]
➜  ~ http --help
Traceback (most recent call last):
  File "/usr/local/Cellar/httpie/0.9.4/libexec/bin/http", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'

**Comment by badjano** [comment]
bump

**Comment by jkbrzt** [comment]
@badjano that's an old version try `brew update && brew reinstall httpie`

**Comment by badjano** [comment]
Traceback (most recent call last):
  File "/usr/local/Cellar/httpie/0.9.6/libexec/bin/http", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named 'pkg_resources'

**Comment by badjano** [comment]
I have a colleague that has the same mac, but it is working on his, I reinstalled python, pip, setuptools, brew upgrade, everything, still can't figure out what is going on

**Comment by sheeley** [comment]
I just ran into this as well. Looking at the install error, I saw this:
```
==> Installing dependencies for httpie: python3
==> Installing httpie dependency: python3
==> Downloading https://homebrew.bintray.com/bottles/python3-3.5.2_1.el_capitan.bottle.2.tar.gz
######################################################################## 100.0%
==> Pouring python3-3.5.2_1.el_capitan.bottle.2.tar.gz
==> Using the sandbox
==> /usr/local/Cellar/python3/3.5.2_1/bin/python3 -s setup.py --no-user-cfg install --force --verbose --install-scripts=/usr/local/Cellar/python3/3.5.2_1/bin --install-lib=/usr/local/lib/python3.5/site-pa
Last 15 lines from /Users/jsheeley/Library/Logs/Homebrew/python3/post_install.01.python3:
-s
setup.py
--no-user-cfg
install
--force
--verbose
--install-scripts=/usr/local/Cellar/python3/3.5.2_1/bin
--install-lib=/usr/local/lib/python3.5/site-packages
--single-version-externally-managed
--record=installed.txt

Failed to import the site module
Your PYTHONPATH points to a site-packages dir for Python 2.x but you are running Python 3.x!
     PYTHONPATH is currently: "/Library/Python/2.7/site-packages:/usr/local/lib/python2.7/site-packages:/Users/jsheeley/.venvburrito/lib/python2.7/site-packages"
     You should `unset PYTHONPATH` to fix this.
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall python3`
==> Caveats
Pip, setuptools, and wheel have been installed. To update them
  pip3 install --upgrade pip setuptools wheel
... (etc)
```

To fix, I ran:
```
✗ unset PYTHONPATH
✗ brew postinstall python3
✗ http google.com
HTTP/1.1 301 Moved Permanently
Cache-Control: public, max-age=2592000
Content-Length: 219
Content-Type: text/html; charset=UTF-8
Date: Fri, 23 Sep 2016 04:34:37 GMT
Expires: Sun, 23 Oct 2016 04:34:37 GMT
Location: http://www.google.com/
Server: gws
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block

<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>301 Moved</TITLE></HEAD><BODY>
<H1>301 Moved</H1>
The document has moved
<A HREF="http://www.google.com/">here</A>.
</BODY></HTML>
```
After installing python3 properly, it works (even with PYTHONPATH set to the old value).

I think this is compounded also by brew's recent 1.0.0 release - it seems to have changed a number of python things for me, and I've had to reinstall a number of packages.

**Comment by badjano** [comment]
Thanks @sheeley, this worked for me, although my python3 wasn't linked and I decided to force uninstall it and install it again, and now it works!

**Comment by windyinsc** [comment]
This happened to me after I upgraded npm from 3.10.10 to 4.0.5... I tried @sheeley solution but it did not work for me. My fix was to `brew uninstall httpie` then `brew install httpie`. Now I'm back to normal. FYI.... This was on my MacBook Pro (Early 2011) running macOS 10.9.5
