### ISSUE TITLE
httpie hangs in MobaXterm

### ISSUE THREAD

**Issue by knilling** [jakubroztocil/httpie#527]
I am attempting to use httpie in [mobaXterm](http://mobaxterm.mobatek.net/) (version 8.6) on Windows 7 Ultimate, but httpie hangs and never returns a result.

![ss](https://cloud.githubusercontent.com/assets/20407777/19347367/6e362696-9116-11e6-95e1-1e328baf1cf6.png)

![ss2](https://cloud.githubusercontent.com/assets/20407777/19347372/72c3817c-9116-11e6-92c3-9c812ff7caf8.png)

I configured mobaXterm to use my Windows PATH, and both python and http are on my path:

![ss3](https://cloud.githubusercontent.com/assets/20407777/19347395/96099982-9116-11e6-8096-9a13a221e0f3.PNG)

![ss4](https://cloud.githubusercontent.com/assets/20407777/19347404/9d7bfd68-9116-11e6-9017-2e13b0b3d8f2.png)

Although httpie does not work in mobaXterm, it does work in cmd.exe:

![ss5](https://cloud.githubusercontent.com/assets/20407777/19347421/b38e19ba-9116-11e6-8154-f6cd9b0a0269.png)

![ss6](https://cloud.githubusercontent.com/assets/20407777/19347422/b5effafc-9116-11e6-8541-d646dffa8ed6.png)

I think this issue might be related to another similar issue that I found on StackOverflow:
http://stackoverflow.com/questions/3250749/using-windows-python-from-cygwin

**Comment by jkbrzt** [comment]
What is the output of `http --debug`?

I think it's the same problem as #453, see this comment: https://github.com/jkbrzt/httpie/issues/453#issuecomment-201704470

**Comment by knilling** [comment]
Here is the output from `http --debug` :

![ss7](https://cloud.githubusercontent.com/assets/20407777/19347922/5fc1aa88-9119-11e6-8a75-c810c8a2acf1.png)

~~~~
http --debug
HTTPie 0.9.6
Requests 2.11.1
Pygments 2.1.3
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (
c:\python27\python.exe
Windows 7

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "u'HTTPie configuration file'",
            "help": "u'https://github.com/jkbrzt/httpie#config'",
            "httpie": "u'0.9.6'"
        },
        "default_options": "[]"
    },
    "config_dir": "C:\\Users\\Chris\\AppData\\Roaming\\\\httpie",
    "is_windows": true,
    "stderr": "<colorama.ansitowin32.StreamWrapper object at 0x02E61D50>",
    "stderr_isatty": false,
    "stdin": "<open file '<stdin>', mode 'r' at 0x004CB020>",
    "stdin_encoding": "utf8",
    "stdin_isatty": false,
    "stdout": "<colorama.ansitowin32.StreamWrapper object at 0x02E61210>",
    "stdout_encoding": "utf8",
    "stdout_isatty": false
}>
~~~~

I just read through #453 , and it does look like the same issue.

`$ python -c 'import sys; print(sys.stdin.isatty())'` returns False for me as well:

![ss8](https://cloud.githubusercontent.com/assets/20407777/19348361/8bcdd3ac-911b-11e6-9ed0-c2cb58ac8743.png)

It might be worth pointing out that I just discovered that if I attempt to run python interactively, it also hangs.  _However_, if I add the -i flag, the python shell works as expected.

![ss9](https://cloud.githubusercontent.com/assets/20407777/19348431/deb62a92-911b-11e6-8277-4f96111983ae.png)

I noticed that HTTPie on windows is actually an exe, versus a plain text python script:
![ss10](https://cloud.githubusercontent.com/assets/20407777/19349229/f28c4462-911f-11e6-992c-4c8eb2046ba6.png)


Just wondering if there are possible hacks that might get HTTPie working on cygwin-based shells.

For example, looking at the strings for http.exe, I noticed that there is a small python script:

![ss11](https://cloud.githubusercontent.com/assets/20407777/19349145/8d6e336a-911f-11e6-83af-22be5b8b77ad.png)

I now realize that #453 was closed because cygwin has its quirks, but I was just wondering...

Is there a way to pass a -i flag into python?

Or is it possible to flush the buffer after HTTPie prints out a line like http://stackoverflow.com/a/3250975

**Comment by jakubroztocil** [comment]
From the debug output I can see that `stdout_isatty` is `False`. If you are still experiencing this problem in 2020, you’ll, unfortunately, need to use `--ignore-stdin`.

**Comment by biggirl45** [comment]
Unsurcribe
