### ISSUE TITLE
Some times Ctrl+C launch a `KeyboardInterrupt` exception traceback in the console

### ISSUE THREAD

**Issue by mrsarm** [jakubroztocil/httpie#531]
Some times when you press `Ctrl+C` to abort the request, this unhandled exception is launched in the console:

```
Traceback (most recent call last):
  File "/usr/local/bin/http", line 7, in <module>
    from httpie.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/httpie/__main__.py", line 6, in <module>
    from .core import main
  File "/usr/local/lib/python2.7/dist-packages/httpie/core.py", line 23, in <module>
    from httpie.client import get_response
  File "/usr/local/lib/python2.7/dist-packages/httpie/client.py", line 8, in <module>
    from httpie import sessions
  File "/usr/local/lib/python2.7/dist-packages/httpie/sessions.py", line 11, in <module>
    from httpie.plugins import plugin_manager
  File "/usr/local/lib/python2.7/dist-packages/httpie/plugins/__init__.py", line 10, in <module>
    from httpie.plugins.manager import PluginManager
  File "/usr/local/lib/python2.7/dist-packages/httpie/plugins/manager.py", line 2, in <module>
    from pkg_resources import iter_entry_points
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2985, in <module>
    @_call_aside
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2971, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws = cls()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1990, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2399, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2740, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2366, in _version_from_file
    return safe_version(value.strip()) or None
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1387, in safe_version
    return str(packaging.version.Version(version))
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
    match = self._regex.search(version)
KeyboardInterrupt
```

I know it's a normal Python exception launched in this circumstance, but it could be silent with a proper `try-except` block. I'm using the latest stable version _0.9.6_.

I test it only with GET operations, without any other param, like `http https://somesite.com`, and the exception is showed only some times.

**Comment by jkbrzt** [comment]
Interesting. Most of HTTPie's [`main()`](https://github.com/jkbrzt/httpie/blob/64f6f69037082581743a736439be731eb4345f96/httpie/core.py#L172) is wrapped in `try-except`, but the `setuptools`-generated console script doesn't have any error handling:

```python
#!/Users/jakub/.virtualenvs/httpie/bin/python3.5
# EASY-INSTALL-ENTRY-SCRIPT: 'httpie','console_scripts','http'
__requires__ = 'httpie'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('httpie', 'console_scripts', 'http')()
    )
```

So when `Ctrl+C` is sent very shortly after invoking `http`, the `KeyboardInterrupt` error doesn't get caught. I wonder if even is a way to customize the generated script.

**Comment by jkbrzt** [comment]
I have made some small tweaks and now `python -m httpie` shouldn't never let `KeyboardInterrupt` errors propagate. But the problem with the `setuptools` console script still persists, though.

**Comment by mrsarm** [comment]
Thanks @jkbrzt , but now I realized that Ctrl+C even doesn't work. Before report this bug I did a script to test the issue like this:

```sh
#!/usr/bin/env bash
echo "Press [CTRL+C] to stop ..."
while true
do
  http http://www.google.com
  sleep 1
done
```

So in this case only pressing Ctrl+C during the `sleep` task works. Now I made two change: remove the `sleep 1` instruction, and change `http` with `python -m httpie` as you suggested, and the Ctrl+C signal doesn't work any more, the process never stop, only shows the `KeyboardInterrupt` traceback. Also using again with `http URL` works the same:

```sh
#!/usr/bin/env bash
echo "Press [CTRL+C] to stop ..."
while true
do
  python -m httpie http://www.google.com
done
```

To be sure this isn't a shell script problem, I made a new script equals to the previous one, but replacing `python -m httpie` with `curl`, and the Ctrl+C behavior works ok.

```sh
#!/usr/bin/env bash
echo "Press [CTRL+C] to stop ..."
while true
do
  curl http://www.google.com
done
```

I ran all these tests with Ubuntu 14.04 64bits, and Python 2.7.6.

**Comment by jkbrzt** [comment]
@mrsarm it has to do with the way Python handles signals. Try this, for example:

```bash
#!/usr/bin/env bash
echo "Press [CTRL+C] to stop ..."
while true
do
  python -c 'import time; time.sleep(1)'
  echo $?
done
```

But I don't know how to make it behave in the expected way, though.

**Comment by mrsarm** [comment]
@jkbrzt Yes in that case doesn't work because you are no handling the `KeyboardInterrupt` exception.

Try this:

#### sleep.sh
```sh
#!/usr/bin/env bash
echo "Press [CTRL+C] to stop ..."
python sleep.py
echo $?
```

#### sleep.py
```python
import time
import sys
try:
    while True: time.sleep(1)
except KeyboardInterrupt:
    sys.stdout.write("\n")
    sys.stdout.flush()
```

Execute `sleep.sh` or just `python sleep.py`: works ok. Then if you remove from `sleep.py` the `KeyboardInterrupt` block, it will fail with the same exception before.

Anyway, I saw you commit c6f2b32e367fc6fc00c926ccda56c8387fb11313, with that change it should works. Maybe there is some native Python call to make the I/O with the network that doesn't handle this very well. But in my project there is also a I/O networking with a MongoDB server and works Ok, even when you call the CLI with the `-f` option to stay open the connection to wait more data. Take a look at the code, I don't see any difference, but maybe you realize something: https://github.com/mrsarm/mongotail/blob/master/mongotail/mongotail.py#L237

**Comment by jkbrzt** [comment]
> in that case doesn't work because you are no handling the `KeyboardInterrupt` exception.

You don't need to handle `KeyboardInterrupt` for a program to quit. The Python program immediately exits with an error status code (like it does with any other unhandled  exception). 

Here the exception gets "handled" and yet the behaviour is exactly the same:

```bash
#!/usr/bin/env bash
echo "Press [CTRL+C] to stop ..."
while true
do
      python -c '
try:
    import time
    time.sleep(1)
except KeyboardInterrupt:
    print("\nCtrl-C")
'
        echo $?
done
```
