### ISSUE TITLE
support store request history 

### ISSUE THREAD

**Issue by lmyyao** [jakubroztocil/httpie#554]
hope httpie support store request history like bash history ,and  can group or tag these histories  like insomnia .

**Comment by dhruvilthakkar** [comment]
Should this be optional like user can set a flag to enable this feature or we should do this by default ?

**Comment by lmyyao** [comment]
maybe setting a tag when request is better. bash history feature !<history_number> is nice

**Comment by jkbrzt** [comment]
This sounds like a useful feature but a bit beyond the scope of HTTPie. There's a [sessions](https://httpie.org/doc#sessions) support which might be slightly useful for this job. 

Check out also [`http-prompt`](https://github.com/eliangcs/http-prompt) — it wraps HTTPie, makes it interactive and adds some nice features.
