### ISSUE TITLE
Feature Request: add streaming to file specified by flag

### ISSUE THREAD

**Issue by hesseljo** [jakubroztocil/httpie#563]
An example might be something like:
http --stream <FLAG> https://github.com/jkbrzt/httpie </filename>

if the <FLAG> contains a name stream to destination without loading into memory. 

else keep download specification like:

http --download https://github.com/jkbrzt/httpie/archive/master.tar.gz

**Comment by jkbrzt** [comment]
What is your specific use case? 

HTTPie streams the output by default [when the output is redirected](https://httpie.org/doc#redirected-output):

```bash
$ http example.org/Movie.mov > Movie.mov
```

You can also [combine redirected output with `--download` for a nicer experience](https://httpie.org/doc#piping-while-downloading). For example:

```bash
$ http -d https://github.com/jkbrzt/httpie/archive/master.tar.gz |  tar zxf -

```
