### ISSUE TITLE
Need Offline install method/package on linux.

### ISSUE THREAD

**Issue by figozhu** [jakubroztocil/httpie#585]
my linux server cannot access internet, when I try "python setup.py install", it's failed with following hint:
`Installed /usr/lib/python2.6/site-packages/httpie-1.0.0_dev-py2.6.egg
Processing dependencies for httpie==1.0.0-dev
Searching for argparse>=1.2.1
Reading http://pypi.python.org/simple/argparse/
Download error: [Errno 101] Network is unreachable -- Some packages may not be found!
Reading http://pypi.python.org/simple/argparse/
Download error: [Errno 101] Network is unreachable -- Some packages may not be found!
Couldn't find index page for 'argparse' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading http://pypi.python.org/simple/
Download error: [Errno 101] Network is unreachable -- Some packages may not be found!
No local packages or download links found for argparse>=1.2.1
error: Could not find suitable distribution for Requirement.parse('argparse>=1.2.1')`

**Comment by sigmavirus24** [comment]
@figozhu The offline package installation for httpie would include:

- Downloading and installing argparse
- Downloading and installing requests
- Downloading and installing Pygments
- Downloading and installing httpie

(Preferably in that order) You can't install something without first having the dependencies installed.
