### ISSUE TITLE
Error at Query String Parameters

### ISSUE THREAD

**Issue by sriyanfernando** [jakubroztocil/httpie#596]
i got these bugs when i tryithis.

![cap12](https://user-images.githubusercontent.com/11556048/28555286-87cfc6de-711c-11e7-8f1b-c5d52ad9f6fc.png)

![cap14](https://user-images.githubusercontent.com/11556048/28555296-9a1af408-711c-11e7-8d8b-70f46f7ba9f3.png)

**Comment by rwish** [comment]
Gives the same error even the exact URL used by Google along with same the query string is used
![googles2](https://user-images.githubusercontent.com/23145920/28555952-9dc2d806-7120-11e7-9503-f616ee009ee5.png)

**Comment by sigmavirus24** [comment]
That is not a bug. That is how your shell works. `&` backgrounds the command process prior to it.

**Comment by shlomif** [comment]
I agree it is not a bug - can it be closed?
