### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by rwish** [jakubroztocil/httpie#597]
Does not log into any site. Gives the same result, i.e. takes to the login page no matter what the credentials are
![testscraper](https://user-images.githubusercontent.com/23145920/28555317-bf763726-711c-11e7-9a44-dcaf4e353b0e.png)

**Comment by sigmavirus24** [comment]
You did not tell us how you attempted to login. Without that, no one can help you.

**Comment by rwish** [comment]
I tried using uname:pword@example.com method and also the httipe's option $ http -a username example.org . They both redirect to the login page only. Can we re-open the issue since I have already started working on it?
