### ISSUE TITLE
Help! Basic auth (-a, --auth) doesn't work with special character in password

### ISSUE THREAD

**Issue by athrunsun** [jakubroztocil/httpie#598]
I was performing a post request with basic auth, using both username and password, the password has a special character `$` in it.
```shell
http -v -a xxx:$S123456 -f POST "blahblah"
```

But it doesn't work and server says "Error 401 Invalid password/token for user:xxx".

I switched to another tool like postman, and I found it generated a different hash in `Authorization: Basic xxx` header, and the request works.

Is it because I used a special character in my password? How should I write the shell command to correctly pass the password to the server?

**Comment by sigmavirus24** [comment]
If your password uses `$` you need to do `-a 'xxx:$S123456'` because most shells interpret `$` as the start of a variable name to use the value of. This has been covered elsewhere in this issue tracker.

**Comment by athrunsun** [comment]
@sigmavirus24 Thanks for your help! It works now.
