### ISSUE TITLE
Python 3  subprocess shell not print

### ISSUE THREAD

**Issue by AllenCoder** [jakubroztocil/httpie#599]
1. when i use shell it works ok 
2. win7 * 64 python 3.5 

```python
import subprocess

command1 ="ipconfig /all"

command2 ="http baidi.com"

subprocess.call(command1, shell = True)
subprocess.call(command2, shell = True)
```

command 1 can print log but cmmand2 not print log

**Comment by jakubroztocil** [comment]
@AllenCoder you will probably have to include `--ignore-stdin` — https://httpie.org/doc#best-practices

**Comment by AllenCoder** [comment]
it work's well ,thanks
