### ISSUE TITLE
No module named 'encodings'

### ISSUE THREAD

**Issue by Ollie-w** [jakubroztocil/httpie#604]
I am on Ubuntu. 
When I tried `http httpie.org` I got the error message:
```
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ff6cfe8b700 (most recent call first):
Aborted (core dumped)

```

**Comment by sigmavirus24** [comment]
`Py_Initialize` is coming from a C extension that you're using. How did you install httpie? Have you tried it inside a virtual environment?

**Comment by eugene-karanda** [comment]
I have the same issue. I have installed by Linuxbrew on Ubuntu 16.04

**Comment by sigmavirus24** [comment]
@eugene-karanda what other things do you have installed into your site-packages?
