### ISSUE TITLE
output formatting on debian...

### ISSUE THREAD

**Issue by fake-fur** [jakubroztocil/httpie#606]
hi and thanks for a great tool :)

i'm not seeing json output formatted as it is in the screenshots here - i get just a single string of json that wraps at the terminal window edge - is there anything i should be doing differently that:

http [domain.blah]

?

thanks

**Comment by jakubroztocil** [comment]
@fake-fur what is the output when you run `http --debug`?

**Comment by fake-fur** [comment]
xxx@DEB420:~$ http --debug
HTTPie 0.9.3
HTTPie data: /home/xxx/.httpie
Requests 2.7.0
Pygments 2.1
Python 3.5.4 (default, Aug 12 2017, 14:08:14) 
[GCC 7.1.0] linux

**Comment by jakubroztocil** [comment]
And this one?
```
python3 -c 'import sys; print(sys.stdout.isatty())'
```

**Comment by jakubroztocil** [comment]
Also, please try: `http --pretty=all domain.blah`

**Comment by fake-fur** [comment]
True

before i use up anymore of your time let me make sure the api is returning data properly headed etc 
thanks again and i will get back when i have investigated further
:)

**Comment by fake-fur** [comment]
just a quick update... the api i am testing was wrapping the json response in an html response, so although it was json the first header was text/html ... as soon as i fixed that all works as it should

so sorry to have bothered you with something so stupid
:|

**Comment by jakubroztocil** [comment]
No worries, glad you've figured that out.
