### ISSUE TITLE
timeout < 30 only?

### ISSUE THREAD

**Issue by pyvotal-cguers** [jakubroztocil/httpie#609]
I am setting timeout to 300 seconds (to test an AWS lambda function + API Gateway), but HTTPie continues to timeout at 30 seconds. Is there an upper limit set at 30 seconds? I'´m using

`http --timeout=300 POST https://...`

**Comment by jasonxia23** [comment]
30 is the default timeout set, not the upper limit.

**Comment by pyvotal-cguers** [comment]
For some reason, `httpie` is not using the timeout I specify and times out at 30 seconds...

```
$ http --timeout=300 POST https://...
HTTP/1.1 504 Gateway Timeout
Connection: keep-alive
Content-Length: 41
Content-Type: application/json
Date: ...

{
    "message": "Endpoint request timed out"
}
```

I tries this with `--timeout=300` and `--timeout 300` (which should not make a difference, but I wanted to make sure) and the results are the same: it times out at 30 seconds. The function call should take around 2 minutes (120 seconds), but it never gets past the 30 seconds.

**Comment by sigmavirus24** [comment]
This is not `httpie` timing out. You're receiving a response that tells you the intermediary between you and your lambda function is timing out the request. `--timeout` is from your computer to that intermediary. The intermediary can set whatever timeout it wants from itself to your lambda function. This is firmly *not* an HTTPie bug.

**Comment by gnulnx** [comment]
Actually this is an issue with httpie.  My gunicorn timeout is 90s and httpie is still stopping at 30s... I know gunicorn isn't timing out because a few seconds after httpie dies I see the server output results in the log.

**Comment by jakubroztocil** [comment]
@gnulnx there's a default 30s _connection_ timeout which you can change via `--timeout=n`.

(The default timeout will be removed in v2.0.0.)
