### ISSUE TITLE
0.9.9 release tag missing

### ISSUE THREAD

**Issue by jelly** [jakubroztocil/httpie#620]
As a packager for Arch Linux it's useful to grab the source from Github instead of PyPi since that version includes tests which can be run when packaging it. So it would be awesome if there was a 0.9.9 tag, thanks! :)

**Comment by eli-schwartz** [comment]
Is it ever intended that this be fixed?

**Comment by anthraxx** [comment]
@jakubroztocil bump

**Comment by jelly** [comment]
Bump, can this still be done, or provide the git commit hash which is 0.9.9

**Comment by jakubroztocil** [comment]
@jelly 👍 tagged — https://github.com/jakubroztocil/httpie/releases/tag/0.9.9 

(0.9.9 only includes some README fixes)
