### ISSUE TITLE
Does default request method change depending on the env?

### ISSUE THREAD

**Issue by korayal** [jakubroztocil/httpie#626]
I noticed something odd while trying to write a cron script.

Executing `http "https://httpbin.org/anything"` in our CLI does a `GET` request, while if I run that same command in a cron script, it becomes a `POST` request. Is this intentional? 

( this can be replicated via sending a similar request to a path in https://requestb.in )

I noticed this on v0.9.4, then upgraded to v0.9.9 and the issue is still there.

**Comment by jakubroztocil** [comment]
You might need to use `--ignore-stdin` when invoking HTTPie from a cron job. Please see the docs for more details — https://httpie.org/doc#scripting.
