### ISSUE TITLE
send multiple json 

### ISSUE THREAD

**Issue by arenasgt** [jakubroztocil/httpie#628]
I am trying to send multiple json objects in a post, I've been reading the documentation but I couldn't   find how to solve it, so I wonder if is this possible? the working curl call(taken from the elasticsearch documentation) is the following:
curl -XPOST 'localhost:9200/customer/external/_bulk?pretty&pretty' -H 'Content-Type: application/json' -d'
{"index":{"_id":"1"}}
{"name": "John Doe" }
{"index":{"_id":"2"}}
{"name": "Jane Doe" }
'
thanks, all.

**Comment by darshanime** [comment]
write the json in a file `foo.json`

```bash
$ http localhost:9200/customer/external/_bulk?pretty&pretty < foo.json
```

**Comment by jakubroztocil** [comment]
@arenasgt HTTPie accepts raw [request data via `stdin`](https://httpie.org/doc#redirected-input), for example:

```bash
# via a redirect from a file (like @darshanime suggests):

http ':9200/customer/external/_bulk?pretty&pretty'  < data.json

```

```bash
# via `echo`

echo '
{"index":{"_id":"1"}}
{"name": "John Doe" }
{"index":{"_id":"2"}}
{"name": "Jane Doe" }
' | http ':9200/customer/external/_bulk?pretty&pretty' 

```


```bash
# in Bash, you can also do this:

http ':9200/customer/external/_bulk?pretty&pretty' <<<'
{"index":{"_id":"1"}}
{"name": "John Doe" }
{"index":{"_id":"2"}}
{"name": "Jane Doe" }
'

```
