### ISSUE TITLE
latency compared to cURL

### ISSUE THREAD

**Issue by alexander-riss** [jakubroztocil/httpie#629]
i noticed that httpie introduces a significant latency compared to using plain cURL.

calling the same URL in cURL vs httpie is about 400 ms slower in httpie.

is there any way to smooth this to make it a more "instant" experience?

**Comment by sigmavirus24** [comment]
@alexander-riss there are many factors that can contribute to that extra 400ms:

1. What version of python you're using
2. What versions of httpie and its dependencies you have installed
3. What version of openssl you have
(and many more)

"Please shave off 400ms on my computer" is practically impossible with what you've provided us. Please provide more detail.

**Comment by alexander-riss** [comment]
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
httpie 0.9.9 (installed via brew)

the connection was against a non SSL localhost server - so not sure if this would be relevant?

**Comment by sigmavirus24** [comment]
> the connection was against a non SSL localhost server - so not sure if this would be relevant?

It is relevant.

**Comment by jakubroztocil** [comment]
@alexander-riss  Possible cause: https://github.com/jakubroztocil/httpie/issues/603. I'd recommend upgrading to Python 3 (default for Homebrew installs).
