### ISSUE TITLE
HTTPie always uses full timeout period before printing results

### ISSUE THREAD

**Issue by dennislaumen** [jakubroztocil/httpie#632]
Hi all!

First off, keep up the good work with HTTPie. It's an amazing tool!

Unfortunately, I just installed HTTPie on a new machine and it's showing some behavior I'm not used to. When doing requests to the API we're developing it always takes the full 30 second timeout before responding in the CLI.

At first I thought something in our API was causing the slow down as we're in the middle of development. This turned out not to be the case however as it's fast when using cURL. When looking in the app logs of our API it seems that the actual request isn't sent until the timeout expires.

This is the request we're doing (obfuscated the URL for our client's sake).

```
$ http --debug --timeout=5 PUT https://rest-api-acc.example.com/v1/just/some/resource interval=900
HTTPie 0.9.9
Requests 2.12.3
Pygments 2.1.3
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
/usr/local/Cellar/httpie/0.9.9/libexec/bin/python3.6
Darwin 16.7.0

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "HTTPie configuration file",
            "help": "https://httpie.org/docs#config",
            "httpie": "0.9.9"
        },
        "default_options": "[]"
    },
    "config_dir": "/Users/dennislaumen/.httpie",
    "is_windows": false,
    "stderr": "<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>",
    "stderr_isatty": true,
    "stdin": "<_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": true
}>

>>> requests.request(**{
    "allow_redirects": false,
    "auth": "None",
    "cert": "None",
    "data": "{\"interval\": \"900\"}",
    "files": {},
    "headers": {
        "Accept": "application/json, */*",
        "Content-Type": "application/json",
        "User-Agent": "HTTPie/0.9.9"
    },
    "method": "put",
    "params": {},
    "proxies": {},
    "stream": true,
    "timeout": "5.0",
    "url": "https://rest-api-acc.example.com/v1/just/some/resource",
    "verify": true
})

HTTP/1.1 204 No Content
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Content-Type: application/json
Date: Tue, 14 Nov 2017 17:05:09 GMT
Expires: 0
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
```

When sending this request with the `--debug` added the initial debug output is displayed immediately. The response takes the whole timeout.

Any help would be appreciated.

Some details:

* Running on macOS.
* Installed with Homebrew.
* Debug output:
```
$ http --debug
HTTPie 0.9.9
Requests 2.12.3
Pygments 2.1.3
Python 3.6.3 (default, Oct  4 2017, 06:09:15)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
/usr/local/Cellar/httpie/0.9.9/libexec/bin/python3.6
Darwin 16.7.0

<Environment {
    "colors": 256,
    "config": {
        "__meta__": {
            "about": "HTTPie configuration file",
            "help": "https://httpie.org/docs#config",
            "httpie": "0.9.9"
        },
        "default_options": "[]"
    },
    "config_dir": "/Users/dennislaumen/.httpie",
    "is_windows": false,
    "stderr": "<_io.TextIOWrapper name='<stderr>' mode='w' encoding='UTF-8'>",
    "stderr_isatty": true,
    "stdin": "<_io.TextIOWrapper name='<stdin>' mode='r' encoding='UTF-8'>",
    "stdin_encoding": "UTF-8",
    "stdin_isatty": true,
    "stdout": "<_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>",
    "stdout_encoding": "UTF-8",
    "stdout_isatty": true
}>
```

**Comment by dennislaumen** [comment]
I found out what the problem was. I'll leave it up to you to close this issue as my problem is solved but something might be able to be improved in HTTPie around this.

So the issue was that the domain I was connecting to had AAAA (IPv6) DNS records but the firewall wasn't allowing traffic on port 443 for the IPv6 address. cURL and other tools work around this by falling back to IPv4 in case of problems. HTTPie also *seems* to do this, but only after the timeout has expired.

I'd think that the cURL behavior is bit more user friendly, especially as most HTTPie users probably don't care whether they're using IPv4 and IPv6. This sounds simple enough, but that is probably easier said than done 😉.

**Comment by tobiashochguertel** [comment]
@dennislaumen thanks!!! for this hint about ipv6! I had exactly the same issue.
