### ISSUE TITLE
Typo on the home page - "OSX"

### ISSUE THREAD

**Issue by shlomif** [jakubroztocil/httpie#634]
On https://httpie.org/ "OSX" should be either "OS X" or alternatively the new name is "macOS".

Thanks for httpie!

**Comment by jakubroztocil** [comment]
Fixed, thanks!

**Comment by shlomif** [comment]
On Sun, 17 Dec 2017 10:46:57 -0800
Jakub Roztocil <notifications@github.com> wrote:

> Fixed, thanks!
> 

you are welcome.

-- 
-----------------------------------------------------------------
Shlomi Fish       http://www.shlomifish.org/
My Photos - http://www.flickr.com/photos/shlomif/

He who has more is not happier than he who wants less.
    — Source unknown, via Nadav Har’El.

Please reply to list if it's a mailing list post - http://shlom.in/reply .
