### ISSUE TITLE
Is there a way to catch response body of a Internal Server Error?

### ISSUE THREAD

**Issue by thiagobucca** [jakubroztocil/httpie#637]
Hello, i need to get the response body of a Http Status Code 500 request, but i need that request itself to be an "exit 0" request. Is there a way to do this with httpie?

Example with curl: 

curl --silent --show-error --fail -X GET --header "Accept: application/json" --header "token:mytoken" "https://myrequest.com" -d """"""

This request returns exit 0 without writing a bash script to parse the status code, but the downside is that i can't get the response body with this aproach.

Is there a way to do what i want with httpie **without** creating a script to parse the status codes?

Thanks in advance

**Comment by jakubroztocil** [comment]
@thiagobucca HTTPie doesn't come with an out-of-the-box solution so a bit of scripting will be necessary.

With `--check-status`, HTTPie exits with the status code  `5` for any `5XX` server error response. You can take an advantage that so you'd end up with something like this:

```bash
BODY=$( http --check-status --ignore-stdin --body https://httpbin.org/status/500 2> /dev/null )
[ $? == 5 ] && echo "$BODY"
```

See more details in the docs — https://httpie.org/doc#scripting.
