### ISSUE TITLE
Binary releases for non-Homebrew aficiados

### ISSUE THREAD

**Issue by mcandre** [jakubroztocil/httpie#640]
Some users are not developers, may not have either Homebrew or Xcode installed in order to compile HTTPie. Could binary releases be published for non-developer mac environments?

**Comment by lambdaupb** [comment]
httpie is not natively compiled but uses python.
Distributing a self-contained python program is non-trivial.

Your best bet is probably to use a python virtualenv or installing it via macports or homebrew.

**Comment by jakubroztocil** [comment]
@mcandre you can always use [`pip install httpie`](https://httpie.org/doc#windows-etc).
