### ISSUE TITLE
Integrate with a reliable Windows CI (other than AppVeyor)

### ISSUE THREAD

**Issue by jakubroztocil** [jakubroztocil/httpie#642]

**Comment by sigmavirus24** [comment]
Is there actually another Windows CI that we can use?

**Comment by jakubroztocil** [comment]
@sigmavirus24 Good question. I haven't done any thorough research yet. Suggestions welcome.

I've removed the AppVeyor integration because it's been broken for a while. I'm unable to make even basic things like `pip install` work anymore.  And their support is unresponsive.

**Comment by sigmavirus24** [comment]
I don't think there is another one sadly

**Comment by jakubroztocil** [comment]
Solved via Github Actions CI, thanks everyone.
