### ISSUE TITLE
[suggestion] Friendly Content-Length representation

### ISSUE THREAD

**Issue by mqudsi** [jakubroztocil/httpie#643]
I'm not sure how this would work in terms of making clear what was actually sent by the server and what has been marked up by httpie, but it would be nice to have a "friendly" representation of the content length in base two units so output along the lines of `http --headers ...` could be more easily understood at a glance.

**Comment by jakubroztocil** [comment]
@mqudsi you can see a human-friendly representation of the download size calculated from `Content-Length` (if provided) with the [download mode](https://httpie.org/doc#download-mode)  enabled (via `--download / -d`):

```bash
$ http --download https://raw.githubusercontent.com/jakubroztocil/httpie/master/httpie.png
```

```http
HTTP/1.1 200 OK
Content-Length: 186489

Downloading 182.12 kB to "httpie.png"
Done. 182.12 kB in 0.07714s (2.31 MB/s)
``` 

The default mode is meant to show the raw headers.
