### ISSUE TITLE
Error: An unexpected error occurred during the `brew link` step

### ISSUE THREAD

**Issue by dobeerman** [jakubroztocil/httpie#645]
I've this errors on the end of install process
...
==> Pouring python3-3.6.4_1.high_sierra.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks

**Comment by sigmavirus24** [comment]
This is not httpie's fault. Your system isn't configured to allow you to install anything in `/usr/local` most likely and that's something you need to fix.

**Comment by dobeerman** [comment]
@sigmavirus24 hmm... other packages is ok.

**Comment by sigmavirus24** [comment]
Please read your output more closely. This is directly related to ` ==> Pouring python3-3.6.4_1.high_sierra.bottle.tar.gz`

**Comment by jakubroztocil** [comment]
@dobeerman this is a Homebrew related issue. Try running `$ brew doctor`.

**Comment by crmendoza093** [comment]
Thanks!!!

**Comment by yogeshpatil143** [comment]
Just Run below command

1)brew doctor

than

sudo chown -R $(whoami) $(brew --prefix)/*

note the $(brew --prefix)/* ...High Sierra doesn't allow you to change permissions on /user/local directly)

then this:

sudo install -d -o $(whoami) -g admin /usr/local/Frameworks

Your problem may be solve

**Comment by kurbeco** [comment]
I was having the same issue, and that fixed it. Thanks

**Comment by KiengKnot** [comment]
For others who have the same problem on linking different package like `dbgm`
1. check `Error: Permission denied @ dir_s_mkdir - [FOLDER_NEED_PERMISSION]`
2. then grant permission as @yogeshpatil143  said

`sudo install -d -o $(whoami) -g admin [FOLDER_NEED_PERMISSION]`

 => grant permission to the folder `[FOLDER_NEED_PERMISSION]`

**Comment by yogeshpatil143** [comment]
Yes you are correct my dear friend.. @KiengKnot ..

**Comment by jacktan1991** [comment]
ref: https://gist.github.com/dalegaspi/7d336944041f31466c0f9c7a17f7d601
