### ISSUE TITLE
when I installed the httpie, but can't command not found 

### ISSUE THREAD

**Issue by xiaomoinfo** [jakubroztocil/httpie#649]
![image](https://user-images.githubusercontent.com/12625278/35658195-07d23f2e-073b-11e8-8194-158607e9d2c8.png)

**Comment by xiaomoinfo** [comment]
I have fixed the problem.  I installed the httpie with pip and my python location is /usr/local/python. I find that all the command file which installed by pip is /usr/local/python/bin. so I add the path to .bashrc, then `http` command is available

**Comment by sigmavirus24** [comment]
@xiaomoinfo please close this issue if you have resolved it

**Comment by seguri** [comment]
And don't skip the warning if you come here in 2023 :)

```
WARNING: The scripts http, httpie and https are installed in '/Users/myuser/Library/Python/3.9/bin' which is not on PATH.
```
