### ISSUE TITLE
MacOs High Sierra - Error during install

### ISSUE THREAD

**Issue by sebastienhouzet** [jakubroztocil/httpie#665]
Hello All,

Impossible to install with Brew On MacOS High Sierra :/

Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied @ dir_s_mkdir - /usr/local/Frameworks
Error: Permission denied @ dir_s_mkdir - /usr/local/Frameworks

**Comment by dalibegovic** [comment]
Hi,

I just installed it today on MacOS High Sierra (using brew), so i would say that the problem is not in the OS version.

**Comment by sebastienhouzet** [comment]
Hi

I have relaunch a seconde time, adn during the seconde time, no error :/

**Comment by dalibegovic** [comment]
there you go :)

You can close the issue if you managed to install it.
