### ISSUE TITLE
Option to Pretty Print JSON Body

### ISSUE THREAD

**Issue by PSLLSP** [jakubroztocil/httpie#667]
There is closed issue #410.
I still miss an option to force httpie to format body in the answer. I see two cases:

1) Misconfigured server. Some REST API services are misconfigured, they report JSON formatted data but with wrong type, like text/plain or text/html or anything else. I cannot do anything about that.

2) New content types could return JSON but until these are known by httpie, data are not formated. For example, application/dns-json

```
$ http --version
0.8.0

$ http 'https://cloudflare-dns.com/dns-query?ct=application/dns-json&name=github.com&type=A'
HTTP/1.1 200 OK
CF-RAY: 405571cf6e0d2b4c-AMS
Connection: keep-alive
Content-Length: 276
Content-Type: application/dns-json
Date: Mon, 02 Apr 2018 18:44:03 GMT
Server: cloudflare-nginx
Set-Cookie: __cfduid=d649572db5862d7d87ba5b2998aaac9191522694643; expires=Tue, 02-Apr-19 18:44:03 GMT; path=/; domain=.cloudflare-dns.com; HttpOnly; Secure
cache-control: max-age=12

{"Status": 0,"TC": false,"RD": true, "RA": true, "AD": false,"CD": false,"Question":[{"name": "github.com.", "type": 1}],"Answer":[{"name": "github.com.", "type": 1, "TTL": 12, "data": "192.30.253.112"},{"name": "github.com.", "type": 1, "TTL": 12, "data": "192.30.253.113"}]}
```

Example of misconfigured service, it reports JSON data with context text/html
$ http 'https://www.coinotron.com/app?action=api'

3) It could be useful to have an option to disable formating (to force text format); it could be useful for troubleshooting or for scripts. I have to use curl in some cases, to see 'raw' data sent by server.

```
$ http --body http://now.httpbin.org
{
    "now": {
        "epoch": 1522697883.2888725, 
        "iso8601": "2018-04-02T19:38:03.288872Z", 
        "rfc2822": "Mon, 02 Apr 2018 19:38:03 GMT", 
        "rfc3339": "2018-04-02T19:38:03.28Z", 
        "slang_date": "today", 
        "slang_time": "now"
    }, 
    "urls": [
        "/", 
        "/docs", 
        "/when/:human-timestamp", 
        "/parse/:machine-timestamp"
    ]
}

$ curl http://now.httpbin.org
{"now": {"epoch": 1522697885.5953357, "slang_date": "today", "slang_time": "now", "iso8601": "2018-04-02T19:38:05.595336Z", "rfc2822": "Mon, 02 Apr 2018 19:38:05 GMT", "rfc3339": "2018-04-02T19:38:05.59Z"}, "urls": ["/", "/docs", "/when/:human-timestamp", "/parse/:machine-timestamp"]}
```

**Comment by jakubroztocil** [comment]
This should work fine with HTTPie v0.9.4+.

<img width="1192" alt="screen shot 2018-11-06 at 11 31 07" src="https://user-images.githubusercontent.com/326885/48058810-b236ca00-e1b7-11e8-9426-42de40bc66a2.png">
