### ISSUE TITLE
Cant read headers and request data from file at the same time

### ISSUE THREAD

**Issue by china-shang** [jakubroztocil/httpie#670]
![2018-04-08 14-38-11](https://user-images.githubusercontent.com/17249688/38464118-c2d404f0-3b3a-11e8-826b-24776ac9aa2f.png)
The file is 
Host:www.google.com
q=something

**Comment by jakubroztocil** [comment]
The `q=something` bit will be interpreted as a data key-value pair. If you want to use it as a query string parameter, then it should be `q==something`. 

https://httpie.org/doc#request-items
