### ISSUE TITLE
Support sending ajax request

### ISSUE THREAD

**Issue by greenlaw110** [jakubroztocil/httpie#675]
Support sending ajax request, for example

```
http --ajax http://localhost:5460/foo
```

The above command shall send a GET request to `http://localhost:5460/foo` with `X-Requested-With` header set to `XMLHttpRequest`

**Comment by sigmavirus24** [comment]
Is it really too much to do `http X-Requested-With:XMLHttpRequest http://localhost:5460/foo`?

**Comment by jakubroztocil** [comment]
Agree with @sigmavirus24, I will just need a function instead of an alias because headers need to come after the URL:

```bash
# ~/.bash_profile
function ajax {
    http "$@" X-Requested-With:XMLHttpRequest
}
```
```bash
$ ajax -v  httpbin.org/get
```

```http
GET /headers HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Host: httpbin.org
User-Agent: HTTPie/1.0.0
X-Requested-With: XMLHttpRequest
```

**Comment by chok** [comment]
In my opinion, it is just a shortcut to a very common use case. In this way, you can also create a function in your bash_profile for basic auth, etc...
