### ISSUE TITLE
HTTPie fails inside of AWS EC2 User Data init script

### ISSUE THREAD

**Issue by pcgeek86** [jakubroztocil/httpie#677]
## Issue Overview

When I run the following httpie command interactively, it works fine:

```
http --download --output /tmp/pwsh.deb https://github.com/PowerShell/PowerShell/releases/download/v6.0.2/powershell_6.0.2-1.ubuntu.16.04_amd64.deb
```

However, when I run the same command in an Amazon Web Services (AWS) EC2 User Data (initialization / bootstrap) script, it fails:

```
[  134.406549] cloud-init[1420]: usage: http [--json] [--form] [--pretty {all,colors,format,none}]
[  134.409552] cloud-init[1420]:             [--style STYLE] [--print WHAT] [--verbose] [--headers] [--body]
[  134.409952] cloud-init[1420]:             [--stream] [--output FILE] [--download] [--continue]
[  134.410377] cloud-init[1420]:             [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
[  134.410865] cloud-init[1420]:             [--auth USER[:PASS]] [--auth-type {basic,digest}]
[  134.411291] cloud-init[1420]:             [--proxy PROTOCOL:PROXY_URL] [--follow] [--verify VERIFY]
[  134.411833] cloud-init[1420]:             [--cert CERT] [--cert-key CERT_KEY] [--timeout SECONDS]
[  134.412694] cloud-init[1420]:             [--check-status] [--ignore-stdin] [--help] [--version]
[  134.413135] cloud-init[1420]:             [--traceback] [--debug]
[  134.413620] cloud-init[1420]:             [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
[  134.414053] cloud-init[1420]: http: error: Cannot use --output, -o with redirected output.
```

Based on #290 and [this documentation](https://github.com/jakubroztocil/httpie#scripting), it sounds like the recommendation is to use the `--ignore-stdin` parameter. However, this isn't a great user experience, and it cost me hours of debugging.

## Recommendation

Instead of the current behavior, I'd recommend finding some way to detect if this parameter is required automatically, based on the shell environment that httpie is running inside of. Another option would be to rename this parameter, or create an alias parameter for it, that clearly indicates its usefulness for non-interactive shell scripts (eg. `--silent` or `--non-interactive`).

As a general rule, I expect that a command that works interactively should also work inside of a shell script.

Regardless of action or inaction, I'm posting this issue for the future benefit of anyone who searches for the same error from httpie. :)

Thanks for creating httpie, and please consider making this minor improvement, to continue its goal of human-friendliness! 🚀 

Cheers,
Trevor Sullivan

**Comment by vn-patriot** [comment]
Hi , I have the same problem but  it works well when i ssh into the server and run the script. 
Still struggling how to make it work, even I have tried with ```ignore-stdin``` mode 

Any recommendation would be appreciated !

**Comment by emugel** [comment]
Completely agree, this is a major problem.

**Comment by jakubroztocil** [comment]
I’m pretty sure this has been resolved by now. Please feel free to reopen if the issue persists in the latest HTTPie version.
