### ISSUE TITLE
Question marks instead of unicode text in iterm2

### ISSUE THREAD

**Issue by levani** [jakubroztocil/httpie#678]
Not sure if this is a items2 issue or httpie but iterm2 displays utf-8 text without an issue when not using httpie.

This is what I get now when the response contains utf-8 text:

<img width="465" alt="question marks" src="https://user-images.githubusercontent.com/184472/39693465-2a204648-51f5-11e8-8190-9e05e432a677.png">

Strange part is this works when using Hyper instead of iterm2...

**Comment by sigmavirus24** [comment]
Duplicate of #671
