### ISSUE TITLE
Can't provide passphrase for p12 cert?

### ISSUE THREAD

**Issue by bedge** [jakubroztocil/httpie#679]
I can't get cert auth working with a p12 cert with a passphrase.
Am I missing an option?

❯ http  --cert <cert filename>: 'https://localhost:20207/....'

http: error: SSLError: [SSL] PEM lib (_ssl.c:3393) while doing GET request to URL: https://localhost:20207/...

1) How can I provide the .p12 passphrase in a config file, or on the cmdline?

2) Is there something else wrong with p12 cert auth or should that work?

Curl works:
❯ curl --cert <cert filename>:<cert passphrase>  'https://localhost:20207/....'

**Comment by sigmavirus24** [comment]
The limitation here fundamentally comes from Python's OpenSSL support. It doesn't support what you want here. Unfortunately that will not work

**Comment by bedge** [comment]
Is it the passphrase that's a problem, or the ssl cert authentication with python in general? 

I believe I can rebuild the cert to not require a passphrase.

**Comment by sigmavirus24** [comment]
The passphrase is the issue. The Python module that provides the interface to OpenSSL doesn't provide anyway for us to provide it to OpenSSL.

**Comment by bedge** [comment]
I embedded the passphrase in the cert and confirmed it works. Thanks for the help!

The only thing I had to do for httpie that wasn't required with curl was add the "--verify=no". 

> ❯ http  --cert tam-master08_np.pem  --verify=no https://localhost:20207/
> HTTP/1.1 200 OK
> Access-Control-Allow-Headers: Content-Type, api_key, Authorization, Location
> Access-Control-Allow-Methods: GET, POST, PUT, DELETE
> Access-Control-Allow-Origin: *
> Access-Control-Expose-Headers: Content-Type, Location, Link, ETag
> Content-Encoding: gzip
> Content-Length: 396
> Content-Type: application/json;charset=UTF-8
> Server: Jetty(9.1.1.v20140108)
> Vary: Accept-Encoding, User-Agent
> 
> [
>     {
>         "_links": {
>             "installedApplication": [
>                 {
> ...
>
