### ISSUE TITLE
support base64 file input

### ISSUE THREAD

**Issue by engin** [jakubroztocil/httpie#680]
hello,

`jo` supports base64 encoding with `%` prefix
```
jo user_id=1 tags=$(jo -a foo) type=1 data=%/path/to/file.bin
```
can httpie support this natively without needing `jo` ?

**Comment by jakubroztocil** [comment]
@engin HTTPie does not natively support base64 encoding. You could achieve the same result by combining `http` and `base64`, though:

```bash
$  http  httpbin.org/post  data=$(base64 < /path/to/file.bin)
```

**Comment by lapo-luchini** [comment]
Actually, httpie it chokes on the newlines that `base64` produces, I managed to do it using `openssl enc -A -base64`.

**Comment by ivmn** [comment]
@lapo-luchini `base64 -w 0` would do as well
