### ISSUE TITLE
Fix Travis / tests

### ISSUE THREAD

**Issue by jakubroztocil** [jakubroztocil/httpie#681]
https://travis-ci.org/jakubroztocil/httpie/jobs/385658131#L598-L616

**Comment by yevgenys** [comment]
@jakubroztocil hi! i'm new to this framework - so not 100% sure that my solution is correct, but tests working :)

**Comment by jakubroztocil** [comment]
Fixed, thanks for your effort, @yevgenys 👍

**Comment by yevgenys** [comment]
@jakubroztocil cool, thx :)
