### ISSUE TITLE
What should I do if i wanna post some fields which including keyword? 

### ISSUE THREAD

**Issue by RudolphBrown** [jakubroztocil/httpie#682]
Like this one:
http POST http://localhost:8080/apis  appId=123 urlPattern=/test  GET=get PUT=put POST=post DELETE=delete

**Comment by jakubroztocil** [comment]
Method names like `GET`, `POST`, etc., are _not_ keywords (you can actually use any  method name you like). The method, if specified, is recognised by its position. So your command will work as expected.
