### ISSUE TITLE
ModuleNotFoundError: No module named '__main__.core'; '__main__' is not a package

### ISSUE THREAD

**Issue by memdreams** [jakubroztocil/httpie#691]
I would like to run the project in pycharm, but it doesn't work. When I run __main__.py which in httpie folder, it just raises the error: ModuleNotFoundError: No module named '__main__.core'; '__main__' is not a package.

So how should I do if I would like to run the code by myself?

**Comment by jakubroztocil** [comment]
If you have HTTPie installed — either globally or in development mode via `pip install --editable` — then you should be able to **point PyCharm directly to the executable**:

```bash
(httpie) ~/Code/httpie $ which http
/Users/jakub/.virtualenvs/httpie/bin/http
```
<img width="889" alt="http" src="https://user-images.githubusercontent.com/326885/43048376-088ec10c-8de7-11e8-96f1-3c19991b66d2.png">

Without installation, you can still invoke HTTPie via **[`python -m`](https://docs.python.org/3/using/cmdline.html#cmdoption-m)** — `$ python -m httpie …`, which you can also achieve from PyCharm (just set the working directory to your local repo location to ensure that `httpie` directory in it is on your `$PYTHONPATH`):

<img width="982" alt="python-m-httpie" src="https://user-images.githubusercontent.com/326885/43048393-3f7686dc-8de7-11e8-895d-cfc3a7a5abba.png">

Note that when you run a script from PyCharm, the process's `stdin` and `stdout` are not connected to a terminal, so rules for [redirected input](https://httpie.org/doc#redirected-input) as well as [redirected output](https://httpie.org/doc#redirected-output) apply. Most importantly, you'll most likely want to include at least the [`--ignore-stdin`](https://httpie.org/doc#best-practices) option.

**Comment by memdreams** [comment]
Thanks so much!
