### ISSUE TITLE
Feature request: support arbitrary HTTP methods

### ISSUE THREAD

**Issue by pauleikis** [jakubroztocil/httpie#693]
Some servers support more than standard list of HTTP methods so I think it would make sense for httpie to support it. I understand it's impossible to support any custom logic for those methods, but code path could be as if no method is provided that is as if it was GET if no data is provided and as if it is POST if any data is provided.

See discussions like https://stackoverflow.com/questions/25857508/what-is-the-http-method-purge
Also IANA has an expanded list of such methods https://www.iana.org/assignments/http-methods/http-methods.xhtml#methods (unfortunately PURGE is not on the list although it's used in popular caching layer - varnish)

curl allows to send any syntactically valid method name in the first line with `-X`.

In my particular case I would like to have support for PURGE method for varnish cache testing and I was suprised httpie cannot do that.

**Comment by dair-targ** [comment]
I've tried to reproduce it using httpbin.org:
```
$ http TEST httpbin.org/anything/x -v
TEST /anything/x HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: httpbin.org
User-Agent: HTTPie/0.9.9



HTTP/1.1 405 METHOD NOT ALLOWED
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Allow: PATCH, DELETE, GET, PUT, TRACE, HEAD, OPTIONS, POST
Connection: keep-alive
Content-Length: 178
Content-Type: text/html
Date: Thu, 01 Nov 2018 05:07:39 GMT
Server: gunicorn/19.9.0
Via: 1.1 vegur

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```
It appears httpie is correctly transmitting any arbitrary HTTP method to the server, e.g. `http ANYMETHOD httpbin.org` would have `ANYMETHOD` to be used in the request.

Would it be possible for you to provide a concrete example when this doesn't work as you expecting?

**Comment by dair-targ** [comment]
Just for the note, I've created [httpbin#522](https://github.com/requests/httpbin/issues/522) so hopefully it would be possible to positive test arbitrary methods there.

**Comment by jakubroztocil** [comment]
@dair-targ thanks
