### ISSUE TITLE
No output of server information when stdin is not present

### ISSUE THREAD

**Issue by pkqxdd** [jakubroztocil/httpie#694]
When stdin is not present, the server information is not printed. The easiest way to reproduce this error is to run
```
import os
os.system("http head example.com")
```
which produces no output. 

Tested on macOS10.13.5 with Python3.6, centOS 6 with Python3.7

**Comment by jakubroztocil** [comment]
@pkqxdd you'll need to include the `--ignore-stdin` option:

> The default behaviour of automatically reading stdin is typically not desirable during non-interactive invocations. You most likely want use the --ignore-stdin option to disable it.
>
> It is a common gotcha that without this option HTTPie seemingly hangs. What happens is that when HTTPie is invoked for example from a cron job, stdin is not connected to a terminal. Therefore, rules for redirected input apply, i.e., HTTPie starts to read it expecting that the request body will be passed through. And since there's no data nor EOF, it will be stuck. So unless you're piping some data to HTTPie, this flag should be used in scripts.

— https://httpie.org/doc#scripting
