### ISSUE TITLE
Do not dump content with first '-v'

### ISSUE THREAD

**Issue by aleksandr-vin** [jakubroztocil/httpie#697]
In cases when either large content is uploaded or when `httpie` is called from a loop, the actual content is not needed to be shown while progress (like headers and status codes is still welcome on the screen).

Now if you use `-v` content will be dumped as well, washing request headers away from the screen and flooding the logs, collected from the screen.

Let's skip content dumping with first `-v` and show it on the second usage, like `-vv`.

**Comment by jakubroztocil** [comment]
@aleksandr-vin you can choose the output via `--print`.  So if you want to print everything except for the request body, then you can specify it with `--print=Hhb`:

```bash
$ echo "this request body won't be shown on terminal" | http --print=Hhb httpbin.org/post 
```
```http
POST /post HTTP/1.1
Accept: application/json, */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 45
Content-Type: application/json
Host: httpbin.org
User-Agent: HTTPie/1.0.0

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Connection: close
Content-Length: 364
Content-Type: application/json
Date: Tue, 06 Nov 2018 09:48:33 GMT
Server: gunicorn/19.9.0

{
    "args": {},
    "data": "this request body won't be shown on terminal\n",
    "files": {},
    "form": {},
    "headers": {
        "Accept": "application/json, */*",
        "Accept-Encoding": "gzip, deflate",
        "Connection": "keep-alive",
        "Content-Length": "45",
        "Content-Type": "application/json",
        "Host": "httpbin.org",
        "User-Agent": "HTTPie/1.0.0"
    },
    "json": null,
    "origin": "127.0.0.1",
    "url": "http://httpbin.org/post"
}
```

https://httpie.org/doc#what-parts-of-the-http-exchange-should-be-printed
