### ISSUE TITLE
upgrade python from 3.6 to 3.7 then switch back broke httpie

### ISSUE THREAD

**Issue by MicroIdea** [jakubroztocil/httpie#707]
Here's what happened:
1. brew upgrade (then I realized python upgrade from 3.6.5 to 3.7.0 and I don't want that)
2. brew switch python 3.6.5 (so I made a downgrade)
3. http
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/httpie/0.9.9_4/libexec/bin/python3.7
  Reason: image not found
[1]    14050 abort      http

After all these I think I broke httpie, how can I fix it?

**Comment by camel113** [comment]
My workaround was to uninstall httpie and re install it.
`brew uninstall httpie`
`brew install httpie`

**Comment by MicroIdea** [comment]
I tried reinstalling httpie and sadly it didn't work, still the same error 😑

**Comment by pulsedemon** [comment]
I'm getting the same error.  I'm on macos 10.14.  At work I have to use python 3.6, so I had to downgrade from 3.7.  It seems like httpie relies on 3.7 explicitly, so I can't use it anymore unless I brew switch, which is too annoying to do. 

```
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/httpie/0.9.9_4/libexec/bin/python3.7
  Reason: image not found
```

I'm sure I could come up with some hacky workaround, but it should work out of the box

**Comment by ihaveadrame** [comment]
I tried reinstalling httpie and sadly it didn't work, still the same error 😑

**Comment by cat-turner** [comment]
+1

**Comment by ejoubaud** [comment]
Installing the latest python fixed it for me:

```
brew install python3
brew switch python 3.7.2_2 # use number of actual version just installed
```
