### ISSUE TITLE
http: error: TypeError: init_poolmanager() got an unexpected keyword argument 'ssl_version'

### ISSUE THREAD

**Issue by Gregster66** [jakubroztocil/httpie#710]
Running on AWS linux with Python 2.7.12 installed.
When I  run my httpie command or save it in a .sh file and run it it completes successfully.
However I'm trying to get an app (Splunk) to periodically run that .sh file and fetch data but it's failing. The app is trying to run the file as the same user that I've tested it with.
This is the error that I'm getting within my app:
http: error: TypeError: init_poolmanager() got an unexpected keyword argument 'ssl_version'

I'm not good with programming so don't even know how to approach it. 
The only other troubleshooting I did was creating a new httpie script that fetches data from a different source just to rule out an issue with the providers endpoints, I still get the same error.

**Comment by jakubroztocil** [comment]
@Gregster66 please try to upgrade to httpie v1 and reopen this issue if the problem persists.
