### ISSUE TITLE
--download does not store response body if http status is not 200

### ISSUE THREAD

**Issue by derFunk** [jakubroztocil/httpie#711]
**Expected:**
Downloading the body of a website, which returns an http error 500, should result in a local file still containing the responses payload. 

**Actual:**
Local file is empty.

**Version:**
```
docker run --rm alpine/httpie --version
0.9.9
```

**Testcase (not working as expected):**
Calling https://httpstat.us/500 should result in having the response body `500 Internal Server Error` stored in the local file.
```
touch test.txt

docker run --rm -t -v "$(pwd)/test.txt":/output.dat \
    alpine/httpie --download \
    --output "/output.dat" \
    GET https://httpstat.us/500

cat test.txt

```

**Counter Testcase (working as expected):**
Calling a website which returns 200 OK is actually being stored when `--download` is used.
```
touch test.txt

docker run --rm -t -v "$(pwd)/test.txt":/output.dat \
    alpine/httpie --download \
    --output "/output.dat" \
    GET https://httpstat.us/200

cat test.txt
200 OK
```

**Comment by jakubroztocil** [comment]
Thanks but `--download` is meant to download files and exit with an error if the server indicates there is one. If you wish to store the response body regardless in a file of the response status code then you can just use `http https://httpstat.us/500 > output.dat`.

**Comment by invoicer-it** [comment]
This shouldn't really be closed. How can we obtain both body and headers if status code is an error? There should be an easy way to do this.

**Comment by rocketraman** [comment]
@jakubroztocil Its confusing and seems wrong that when `--download` is specified, the client *loses* the response body entirely on an error condition: neither is the error content downloaded, nor is it shown on the terminal.

What about showing the body on the terminal on non-zero exit statuses? `--download` does nothing anyway in this situation, and the headers are already shown on the terminal, so I don't think there would be amy harm in showing the error response body as well.

I'm using 3.2.1 on Fedora 37.
