### ISSUE TITLE
Ability to set headers when following redirects

### ISSUE THREAD

**Issue by BrandonY** [jakubroztocil/httpie#712]
Sometimes I am trying to write some requests for APIs that involve redirects. I need a way to specify headers that should be included in the request that follows the redirect reply.

For example, `http https://developer-api.nest.com "Authorization: Bearer 1234.mycredentials"` will result in a redirect. I want to repeat the request after following the redirect, so I include the `--follow` parameter. This is great, except that the followup request will not include the header. That's a very reasonable safety precaution; it probably should not do that by default, at least cross-domain. However, I need some way to provide credentials to the second request in some manner.

I'd like to see this implemented with a  "--follow-with-headers" flag or some such. cURL solves this problem by providing a "--location-trusted" flag which allows credentials to be used on follow-up requests.

**Comment by jakubroztocil** [comment]
Hey @BrandonY, this looks like a use case for https://httpie.org/docs#sessions

For example:

```bash
$ http --session=./my-auth.json --all --print=H --follow httpbin.org/absolute-redirect/1 Authorization:TEST
```

Notice that the `Authorization: TEST` header is included in both requests:

```http
GET /absolute-redirect/1 HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: TEST
Connection: keep-alive
Host: httpbin.org
User-Agent: HTTPie/2.2.0-dev

GET /get HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Authorization: TEST
Connection: keep-alive
Host: httpbin.org
User-Agent: HTTPie/2.2.0-dev
```

You can now inspect / edit the generated session file:

```bash
$ cat my-auth.json
```

```json
{
    "__meta__": {
        "about": "HTTPie session file",
        "help": "https://httpie.org/doc#sessions",
        "httpie": "2.2.0-dev"
    },
    "auth": {
        "password": null,
        "type": null,
        "username": null
    },
    "cookies": {},
    "headers": {
        "Authorization": "TEST"
    }
}
````
