### ISSUE TITLE
Proposal: Allow Auth Plugins to use netrc

### ISSUE THREAD

**Issue by labeneator** [jakubroztocil/httpie#718]
Based on a previous issue #162  and my use case, I'd like to propose a small extension to auth plugins to allow netrc credentials.

Use Case
-----------

We have a [plugin](https://github.com/east36/httpie-http-signatures) that provides [http-signatures](https://tools.ietf.org/html/draft-cavage-http-signatures-10) support to httpie. However, providing an access/secret key pair becomes cumbersome, especially once one has multiple environments to work with (local dev/integ/prod....). 
It would be great if we could leverage .netrc as a store for credentials (instead of creating yet another config file).

Proposal
----------

1. Add a class variable netrc_parse with a default of False to class AuthPlugin. Default of False to support the `principle of least astonishment` (Existing plugins will not be impacted). 
2. If netrc_parse is True, source credentials from .netrc and call get_auth with them.

**Comment by labeneator** [comment]
Sample run

```
❯ tail -1 ~/.netrc
machine api.integ.xxxx.co.ke login akxxxxxxxx password skxxxxxxxxx

# netrc credentials used
 ❯ http   --auth-type=httpsig  "https://api.integ.xxxx.co.ke/api/v1/user/reports" 
HTTP/1.1 200 OK
....
.....


# Credentials from --auth
 ❯ http   --auth-type=httpsig --auth="akxxxxxxxx:skxxxxxxxxx"  "https://api.integ.xxxx.co.ke/api/v1/user/reports"
HTTP/1.1 200 OK
......
......


# Site that doesn't exist in .netrc (no deviation from current httpie behaviour)
 ❯ http   --auth-type=httpsig  "https://api.xxxx.co.ke/api/v1/user/reports" 
usage: http [--json] [--form] [--pretty {all,colors,format,none}]
            [--style STYLE] [--print WHAT] [--headers] [--body] [--verbose]
            [--all] [--history-print WHAT] [--stream] [--output FILE]
            [--download] [--continue]
            [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest,httpsig}]
            [--proxy PROTOCOL:PROXY_URL] [--follow]
            [--max-redirects MAX_REDIRECTS] [--timeout SECONDS]
            [--check-status] [--verify VERIFY]
            [--ssl {ssl2.3,tls1,tls1.1,tls1.2}] [--cert CERT]
            [--cert-key CERT_KEY] [--ignore-stdin] [--help] [--version]
            [--traceback] [--default-scheme DEFAULT_SCHEME] [--debug]
            [METHOD] URL [REQUEST_ITEM [REQUEST_ITEM ...]]
http: error: --auth required

```

**Comment by labeneator** [comment]
@jakubroztocil PR updated.

**Comment by emagutu** [comment]
@jakubroztocil can this be merged please?

**Comment by jakubroztocil** [comment]
Just pushed support for this to `master` in b865988. Feedback appreciated!

@labeneator: I based it on your PR #719, so please feel free to add yourself to `AUTHORS`.
