### ISSUE TITLE
Failing tests on Gentoo Linux

### ISSUE THREAD

**Issue by rseichter** [jakubroztocil/httpie#729]
I recently "adopted" the Gentoo Linux net-misc/httpie package after the last maintainer called it quits, and while I have completed the 1.0.0 binary release, I am having some problems with failing tests:

```
tests/test_binary.py::TestBinaryResponseData::test_binary_suppresses_when_terminal FAILED
tests/test_binary.py::TestBinaryResponseData::test_binary_suppresses_when_not_terminal_but_pretty FAILED
tests/test_binary.py::TestBinaryResponseData::test_binary_included_and_correct_when_suitable FAILED
tests/test_ssl.py::TestClientCert::test_cert_file_invalid FAILED
tests/test_ssl.py::TestClientCert::test_cert_ok_but_missing_key FAILED
tests/test_ssl.py::TestServerCert::test_verify_custom_ca_bundle_invalid_bundle FAILED
```

Full build log file: [httpie-1.0.0-r1:20181113-141909.log](https://github.com/jakubroztocil/httpie/files/2576992/httpie-1.0.0-r1.20181113-141909.log)

Some of the tests seem to fail because they are executed in Gentoo's test sandbox which blocks network connections beyond the build machine. Is it possible to execute only tests which are unaffected by this limitation? I did not find this mentioned in the HTTPie docs, but I'd rather not disable tests by patching if there is a better way.

As for SSL tests, I am not yet fully certain what is causing the failures, so I'd appreciate pointers in this area as well. Thanks.

**Comment by jakubroztocil** [comment]
@rseichter I've released v1.0.1 that doesn't call any external URLs from tests anymore: https://github.com/jakubroztocil/httpie/releases/tag/1.0.1

As for the SSL, I haven't encountered errors like those but I'd try to experiment with upgrading `requests` (https://packages.gentoo.org/packages/dev-python/requests) to the latest version.

**Comment by rseichter** [comment]
@jakubroztocil Thank you, the updated tests of release 1.0.1 no longer cause issues with the sandbox.

Regarding the failing SSL tests: I tried the latest available version of dev-python/requests (2.19.1-r1), but it did not help. If I read things correctly, the three affected tests expect exceptions of the type `requests.exceptions.SSLError`, but according to the build logs, the returned objects are of the type `OpenSSL.SSL.Error` and raised in OpenSSL/SSL.py in load_verify_locations. Is this interpretation correct? Should the requests package re-wrap the OpenSSL exceptions?

**Comment by rseichter** [comment]
I created the following patch as a workaround, but I am not certain it is the proper thing to do:

```patch
--- a/tests/test_ssl.py	2018-11-14 15:41:44.483033341 +0100
+++ b/tests/test_ssl.py	2018-11-14 15:48:05.643051516 +0100
@@ -1,5 +1,6 @@
 import os

+import OpenSSL
 import pytest
 import pytest_httpbin.certs
 from requests.exceptions import SSLError
@@ -57,12 +58,12 @@
         assert 'No such file or directory' in r.stderr

     def test_cert_file_invalid(self, httpbin_secure):
-        with pytest.raises(SSLError):
+        with pytest.raises(OpenSSL.SSL.Error):
             http(httpbin_secure + '/get',
                  '--cert', __file__)

     def test_cert_ok_but_missing_key(self, httpbin_secure):
-        with pytest.raises(SSLError):
+        with pytest.raises(OpenSSL.SSL.Error):
             http(httpbin_secure + '/get',
                  '--cert', CLIENT_CERT)

@@ -95,5 +96,5 @@
             http(httpbin_secure.url + '/get', '--verify', '/__not_found__')

     def test_verify_custom_ca_bundle_invalid_bundle(self, httpbin_secure):
-        with pytest.raises(SSLError):
+        with pytest.raises(OpenSSL.SSL.Error):
             http(httpbin_secure.url + '/get', '--verify', __file__)
```

**Comment by jakubroztocil** [comment]
@rseichter just pushed a fix — the tests didn't take into account pyOpenSSL's errors, which is an optional dependency. Can you please try it again with my latest commit?

**Comment by rseichter** [comment]
@jakubroztocil : I created a patch for test_ssl.py based on release 1.0.1 and your commit, to replace my patch shown above, and the tests succeed on my build machine. Looks good to me.

**Comment by jakubroztocil** [comment]
@rseichter https://github.com/jakubroztocil/httpie/releases/tag/1.0.2

**Comment by rseichter** [comment]
Thanks @jakubroztocil for fixing the test issues so quickly!
