### ISSUE TITLE
[Feature] Allow bypassing .netrc

### ISSUE THREAD

**Issue by gregschibsted** [jakubroztocil/httpie#730]
The default support for .netrc is super useful, but sometimes I'd like to set the Authorisation header to a different value than the one I have configured in my .netrc, and sometimes it would be nice not to Authorization header set, to see how an API behaves when not authorised.

Having a flag, say `--ignore-netrc` that enables this behaviour would be nice. 
Having an Authorization header supplied as a CLI parameter take precedence over what's in .netrc would be nice too.

If you use curl with -n (to enable using .netrc) and also set `-H "Authorization: Bearer abcdef"` then the CLI version of the header takes precedence, and the values from .netrc aren't used.

**Comment by jakubroztocil** [comment]
Thanks, @gregschibsted . `--ignore-netrc` is now implemented in `master`.
