### ISSUE TITLE
Use exact text from the three-clause BSD license

### ISSUE THREAD

**Issue by blast-hardcheese** [jakubroztocil/httpie#740]
The text in `LICENSE` is very close to the BSD 3-clause license, but not exactly, possibly creating some ambiguity in enforcement:

```diff
-THIS SOFTWARE IS PROVIDED BY THE   COPYRIGHT HOLDERS   AND CONTRIBUTORS "AS IS"
+THIS SOFTWARE IS PROVIDED BY THE   AUTHOR              AND CONTRIBUTORS "AS IS"
```

```diff
-IN NO EVENT SHALL THE   COPYRIGHT HOLDER   OR    CONTRIBUTORS BE LIABLE FOR
+IN NO EVENT SHALL THE   AUTHOR             AND   CONTRIBUTORS BE LIABLE FOR
```

The implication of switching `OR` to `AND` could be significant. I found this while attempting to add httpie to [nixpkgs](https://github.com/NixOS/nixpkgs), and I am required to provide a license.

**Comment by jakubroztocil** [comment]
Fixed, thank you
