### ISSUE TITLE
Output to stdout on success, stderr on error

### ISSUE THREAD

**Issue by barnardb** [jakubroztocil/httpie#744]
A common use case I have when scripting is that I'm only able to proceed when I get a 2xx response. The `--check-status` flag is great in this case. However, when a script dies with exit status 4 or 5, I'm not left with much insight about what went wrong. What I would love to be able to have the output go to stdout when the request succeeds, but go to stderr (ideally with headers and formatting, but even just the body would be nice) when it fails.

Is it possible to achieve this with the existing options?

If not, would you consider adding such a feature?

**Comment by jakubroztocil** [comment]
@barnardb It’s not possible to swap the output stream based on the exit status via the existing --options. You’ll need to add the logic to your script I’m afraid, something like:

```bash
# 1. gather output
OUTPUT=$(http --check-status --print=hb httpbin.org/status/418  2> /dev/null)
```


Without the `2> /dev/null` bit, the following warning would go to `stderr`:

```
http: warning: HTTP 418 I'M A TEAPOT
```

```bash
# 2. decide where it should go based on the exit status code.
if [ $? ] ; then 
    echo "$OUTPUT"; 
else
    echo "$OUTPUT" > /dev/stderr; 
fi
```

```http
HTTP/1.1 418 I'M A TEAPOT
Connection: keep-alive
Server: gunicorn/19.9.0
Date: Sun, 03 Feb 2019 12:46:22 GMT
X-More-Info: http://tools.ietf.org/html/rfc2324
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Content-Length: 135
Via: 1.1 vegur


    -=[ teapot ]=-

       _...._
     .'  _ _ `.
    | ."` ^ `". _,
    \_;`"---"`|//
      |       ;/
      \_     _/
        `"""`
```

I think changing the stream would not be super intuitive. Also,`stderr` is already used for warning/error messages.
