### ISSUE TITLE
httpie creates a dir + file in the user's home directory on every execution

### ISSUE THREAD

**Issue by raiskila** [jakubroztocil/httpie#748]
Hi,

Thanks for the great work on this project.

Is there any particular reason why httpie creates the file "~/.httpie/config.json" on every execution?

Could this be put behind a CLI flag like `--init-config`, if people want an easy way to create a blank configuration file? This way httpie could avoid polluting the home folder unless the user wants to override a config setting or use a feature like named sessions.

**Comment by jakubroztocil** [comment]
Thanks for your comment. This behaviour simply a design decision. This behaviour present in many other tools.  HTTPie creates the config file only if it doesn't already exist so there’s no bug here. But I see your point and take your comment as a feature request that I might consider in the future.
