### ISSUE TITLE
Use `--pretty=format` by default even on redirect

### ISSUE THREAD

**Issue by akkartik** [jakubroztocil/httpie#755]
I've read https://github.com/jakubroztocil/httpie#redirected-output and https://github.com/jakubroztocil/httpie#interface-design about how the default is `--pretty=none` for default, and why this default exists (to avoid polluting output for other programs with color escapes). However, this rationale don't seem to apply to `--pretty=format`. Is there any reason not to default redirected output to `--pretty=format`?

Alternatively, we could make --pretty take an optional second comma-separated value for when it's redirected. `--pretty=all` would get expanded to `--pretty=all,all`, but `--pretty=all,format` would change the default for redirected output. This way we wouldn't change the default for everyone, but people willing to change configuration files or shell aliases would be able to type in fewer flags and have commands work whether redirected or not.

Let me know if either of these seem like a good idea, and I'll try to contribute a PR. Thanks.

**Comment by jakubroztocil** [comment]
@akkartik thanks for bringing this up, however, this change is not planned.
