### ISSUE TITLE
Make POST call with XML payload with HTTPie

### ISSUE THREAD

**Issue by crmpicco** [jakubroztocil/httpie#759]
Is there equivalent way to make this cURL call with HTTPie? 

`curl -k -d '<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>wp.getUsersBlogs</methodName><params><param><value>user</value></param><param><value>pass</value></param></params></methodCall>' https://crmpicco.co.uk/xmlrpc.php`

I have tried the following without any success:

`http --pretty=all --verify=no POST https://crmpicco.co.uk/xmlrpc.php data="<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>wp.getUsersBlogs</methodName><params><param><value>admin</value></param><param><value>pass</value></param></params></methodCall>"`

Is there an equivalent? I prefer using HTTPie, but in this instance i've had to fallback to cURL.

**Comment by da2x** [comment]
> http POST https://crmpicco.co.uk/xmlrpc.php '<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>wp.getUsersBlogs</methodName><params><param><value>admin</value></param><param><value>pass</value></param></params></methodCall>'

**Comment by jakubroztocil** [comment]
https://httpie.org/doc#redirected-input

```bash
http POST https://crmpicco.co.uk/xmlrpc.php <<<'<?xml version="1.0" encoding="UTF-8"?><methodCall><methodName>wp.getUsersBlogs</methodName><params><param><value>admin</value></param><param><value>pass</value></param></params></methodCall>'

```
