### ISSUE TITLE
Non-string JSON fields syntax convert strings into numbers

### ISSUE THREAD

**Issue by ibc** [jakubroztocil/httpie#760]
```bash
$ http -v POST https://google.com id:="1111" name="FOO" device:='{"qwe": 2222}'
```

It sends the following POST body:

```json
{
    "device": {
        "qwe": 2222
    },
    "id": 1111,
    "name": "FOO"
}
```

Everything is nice except `id` field which is converted to number.

**Comment by ovsienkonikita** [comment]
Try 
 ```shell
 $ http -v POST https://google.com id="1111" name="FOO" device:='{"qwe": 2222}'
 ```
string is not json object, so u don't need to set value via ":=", just "=" is enoght

**Comment by jakubroztocil** [comment]
> Non-string JSON fields syntax convert strings into numbers

One might argue that a string is not a non-string 😁

You use `=:` when the _don't_ want a string, so what @ovsienkonikita suggests above is correct.
