### ISSUE TITLE
[Question] Repoonse returns taks and then returns actual response.

### ISSUE THREAD

**Issue by loneshark99** [jakubroztocil/httpie#764]
When I run a certain request I get the following output.

http http://someapi.com?
[1] 123
[2] 124

Then after few seconds, the actual json response of the api is shown on the screen, what does this mean. Is it like a queued task and it gives me the prompt back because it will take few seconds to get parse the reponse.

Can someone help me understand the response. 

Thanks.

**Comment by jakubroztocil** [comment]
What URL are you calling?
