### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by newfinal100** [jakubroztocil/httpie#765]
Hello! I was just reading through your project and I'd like to contribute to it by designing a logo. If you'd want that too, please let me know if there are any specific things you'd want this logo to represent, and if you don't have any I'll just implement my own ideas. Looking forward to hearing from you :)

**Comment by jakubroztocil** [comment]
Thanks for the kind proposal, @newfinal100! We have a fairly recent logo, though:

![image](https://user-images.githubusercontent.com/326885/85079930-3c367980-b1c8-11ea-96b4-62cda970748f.png)
