### ISSUE TITLE
Implicit json post does not send content, `--form POST` required

### ISSUE THREAD

**Issue by littlebenlittle** [jakubroztocil/httpie#769]
I'm testing a webapp2 server and found that the server-side request object was always empty. I found [this answer](https://stackoverflow.com/questions/33128993/how-to-send-a-post-request-using-httpie) which provides a workaround.

`http :8080/api/test arg1=val1 arg2=val2` does **not** work

`http --form POST :8080/api/test arg1=val1 arg2=val2` **does** work

Is this working as intended or is it a bug?

**Comment by LuckyDenis** [comment]
It seems to me that by default we execute GET request, on it the request body and shouldn't come, it just also carry out POST requests. But this is only a guess.

**Comment by mustafaemirtan** [comment]
I tested it with these codes:
```python
from bottle import route, request, run


@route("/", method="POST")
def main():
    name = request.forms.get("name")
    return f"Hello {name}!"


run(host="localhost", port=5600)
```

```
C:\>http POST :5600 name=Mustafa
HTTP/1.0 200 OK
Content-Length: 11
Content-Type: text/html; charset=UTF-8
Date: Sat, 27 Jul 2019 13:39:04 GMT
Server: WSGIServer/0.2 CPython/3.7.3

Hello None!
```
As you see, it didn't send any data.
But when I write:
```
C:\>http POST :5600 name=Mustafa --form
HTTP/1.0 200 OK
Content-Length: 14
Content-Type: text/html; charset=UTF-8
Date: Sat, 27 Jul 2019 14:35:55 GMT
Server: WSGIServer/0.2 CPython/3.7.3

Hello Mustafa!
```
I will send a PR for make --form default.

**Comment by memory-yancy** [comment]
@mustafaemirtan  You should use `request.json` not `request.forms`, not a bug. See `README.md`: https://github.com/jakubroztocil/httpie#request-items 
> README.md
>
> Data Fields field=value, field=@file.txt | Request data fields to be serialized as a JSON object (default), or to be form-encoded (--form, -f).

 Details also refer to: `http --debug :5600 name=Mustafa`

**Comment by jakubroztocil** [comment]
This is the intended behaviour (json by default, form with `--form`).
