### ISSUE TITLE
change website install part to show it's supported on multiple platform

### ISSUE THREAD

**Issue by Grummfy** [jakubroztocil/httpie#773]
Hello,
I find confusing that on the website when you click on install you see on https://httpie.org/#installation " brew install httpie "
It make the impression it's only for mac.

Adding a link to other platform (documentation) or simply tabs with mac/linux/windows/pip/other could solve it.

**Comment by Grummfy** [comment]
no answer?

**Comment by jakubroztocil** [comment]
Fixed 😉 

![image](https://user-images.githubusercontent.com/326885/60014589-a41fb600-9681-11e9-872e-8f3b3602b2aa.png)

**Comment by Grummfy** [comment]
thanks
