### ISSUE TITLE
JSON keys containing a "@" symbol are hidden

### ISSUE THREAD

**Issue by dunglas** [jakubroztocil/httpie#774]
It's especially annoying when dealing with JSON-LD document (by the spec reserved keywords start by a `@`).

![image](https://user-images.githubusercontent.com/57224/57728827-17063c00-7695-11e9-81ca-cf884690cc5d.png)

When highlighting:

![image](https://user-images.githubusercontent.com/57224/57728781-00f87b80-7695-11e9-913b-ceb3cb40edb7.png)

Setup: Mac OS, iterm2, ZSH.

**Comment by LuckyDenis** [comment]
Hello. It seems that this is a terminal configuration problem, not a library one. I tried to play on my mac and I had no problems. This is also indicated by the behavior when selecting the response text.

**Comment by dunglas** [comment]
Good catch @LuckyDenis. The color of keys starting with a `@` is black. It's weird because it's not the case for other keys (not starting with a `@`). It works well on a light background, but not on a dark one.

**Comment by dunglas** [comment]
Here are  screen

**Comment by LuckyDenis** [comment]
@dunglas, thanks. I would still `curl -v` checked.

**Comment by jakubroztocil** [comment]
It's most likely that your terminal color scheme, which HTTPie adopts by default, doesn't play well with the highlighter. I'd try to tweak the terminal colors or explicitly specify a style to use in the config file (in your case the bundled `solarized` might do the trick):

```json
{
    "default_options": [
        "--style=solarized"
    ]
}
```


https://httpie.org/doc#configurable-options


See `$ http --help` for all available styles.
