### ISSUE TITLE
Empty headers get dropped silently

### ISSUE THREAD

**Issue by EvanTheB** [jakubroztocil/httpie#783]
Empty headers are silently dropped from a request:

`http -v https://example.org/api X-Token:`

This command will not have an X-Token. This is correct, because RFC 7230 says empty headers are invalid. 

However the user probably intended to include the header (mistaken shell quoting, empty output of subshell, forgotten TODO etc...). An error and message would be improved behaviour. 

```
http -v https://example.org/api X-Token:
Error Header: 'X-Token' was provided without a value, which is invalid. 
(exit status != 0)
```

**Comment by jakubroztocil** [comment]
Please see https://httpie.org/doc#empty-headers-and-header-un-setting

```sh
$ http -v https://example.org/api 'X-Token;'
```
