### ISSUE TITLE
Failing test due to SSLv3 during Gentoo Linux stabilisation

### ISSUE THREAD

**Issue by rseichter** [jakubroztocil/httpie#784]
A [Gentoo bug](https://bugs.gentoo.org/686306) was filed during a [stabilisation](https://wiki.gentoo.org/wiki/Stable_request) attempt for httpie 1.0.2 on Gentoo Linux. As I noted in the comment, it might be related to #647 but I am not fully certain.

Looks like the test fails with "sslv3 alert handshake failure" instead of gracefully skipping over pytest-httpbin's incompatibility with SSLv3, which would need to be solved within the existing httpie tests and not in Gentoo.

**Comment by jakubroztocil** [comment]
Thanks for the report, @rseichter. I think this has just been fixed in master with https://github.com/jakubroztocil/httpie/commit/e93de1fbe7cc811735137fab037a52d6761c7f9e.

**Comment by rseichter** [comment]
I'll try to test this over the coming days. My own temporary "fix" was [a patch](https://github.com/gentoo/gentoo/pull/12352/files?file-filters%5B%5D=.patch) that extends the expected substring.
