### ISSUE TITLE
Warnings shows up on Lastest Manjaro linux

### ISSUE THREAD

**Issue by AlexiaChen** [jakubroztocil/httpie#785]
kernel: 5.0.15-1-MANJARO

/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

But this two dependencies version look like correct:
 pacman -Qi python-chardet python-urllib3
Name            : python-chardet
Version         : 3.0.4-2
Description     : Python3 module for character encoding auto-detection
Architecture    : any
URL             : https://github.com/chardet/chardet
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : python-setuptools
Optional Deps   : None
Required By     : python-requests
Optional For    : python-beautifulsoup4  ranger
Conflicts With  : None
Replaces        : None
Installed Size  : 1143.00 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : 2018年06月30日 星期六 16时56分45秒
Install Date    : 2018年11月24日 星期六 22时00分00秒
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

Name            : python-urllib3
Version         : 1.25.2-1
Description     : HTTP library with thread-safe connection pooling and file post support
Architecture    : any
URL             : https://github.com/shazow/urllib3
Licenses        : MIT
Groups          : None
Provides        : None
Depends On      : python
Optional Deps   : python-pysocks: SOCKS support
                  python-brotlipy: Brotli support
                  python-pyopenssl: security support
Required By     : python-pip  python-requests
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 799.00 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : 2019年04月29日 星期一 23时18分09秒
Install Date    : 2019年05月18日 星期六 18时18分08秒
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

**Comment by jakubroztocil** [comment]
Thannks, @AlexiaChen, but this is something that the packager should look into.
