### ISSUE TITLE
Http headers colors should be based on status code only

### ISSUE THREAD

**Issue by Guillaume-Mayer** [jakubroztocil/httpie#811]
As I commented in #735, some servers (eg Tomcat) don't return the reason-phrase, and it seems valid not to ([RFC 7230](https://tools.ietf.org/html/rfc7230#page-22)).
So "200" (instead of "200 OK") should not render headers in red, I think.

**Comment by jakubroztocil** [comment]
Thanks for the explanation. I’ve submitted a pull request to Pygments, the underlying highlighting library — https://github.com/pygments/pygments/pull/1322.

**Comment by jakubroztocil** [comment]
My PR has already been merged so the fix should be included Pygments 2.5.3 once released (https://pypi.org/project/Pygments/#history).

**Comment by Josholith** [comment]
Your PR to pygments fixed cases of "HTTP/1.1 200" but not the (RFC 7230 compliant) "HTTP/1.1 200 " (trailing whitespace after the status code).  Most notably Tomcat implements HTTP status lines this way, so I was still getting the red headers with HTTPie 2.0.0 and pygments 2.6.1.

To fix this, I've submitted a PR upstream to pygments https://github.com/pygments/pygments/pull/1432

**Comment by Josholith** [comment]
The above PR to pygments has been merged and landed in Pygments 2.7.0.  If you are using HTTPie with Pygments 2.7.0 or later,  the original issue should not be happening.
