### ISSUE TITLE
Is there a way to bypass the param in CURL  post api command and pass it through Body?

### ISSUE THREAD

**Issue by rbarot** [jakubroztocil/httpie#816]
Currently I am using 

`C:\Curl\curl-7.67.0-win32-mingw\bin\curl.exe -H "Content-Type: application/json" -X POST "https://graph.facebook.com/v4.0/550240362387516/events?upload_tag="store_data"&access_token=xxxxxxxxxxxxxxx" -data "@C:\temp\Test.txt" `

which is giving me an error as parameter required.Required Parameter are "upload_tag" and "data".Given that  I don't  want to upload the 1 record at a time. is there a way where body(file) can be passed as a param from local system?

**Comment by jakubroztocil** [comment]
Can you please elaborate?

**Comment by jakubroztocil** [comment]
@rbarot I think you want to report this here instead: https://github.com/curl/curl
