### ISSUE TITLE
httpie in Scoop

### ISSUE THREAD

**Issue by Restia666Ashdoll** [jakubroztocil/httpie#817]
Warning : Uninstall Python if you dont have it installed through Scoop.
I havent yet made a pull request(I guess this qualifies for the main bucket) to scoop but you can install and test it by
`scoop install https://gist.githubusercontent.com/Restia666Ashdoll/147a46b3d8d7a91eb53c8c1c7824d9b7/raw/httpie.json`
And uninstall with `scoop uninstall httpie`
https://gist.github.com/Restia666Ashdoll/147a46b3d8d7a91eb53c8c1c7824d9b7

**Comment by Restia666Ashdoll** [comment]
I updated it a bit. If you have Python installed from external source, you can now use `scoop install https://gist.githubusercontent.com/Restia666Ashdoll/147a46b3d8d7a91eb53c8c1c7824d9b7/raw/httpie.json -i` instead, this will ignore the python dependency(and throw an error if you dont have Python installed).

**Comment by Restia666Ashdoll** [comment]
So, I did make a pull request. Sadly, it was rejected by Scoop mods
https://github.com/ScoopInstaller/Main/pull/648

**Comment by acabarbaye** [comment]
Could we try again. It would be so much helpful
