### ISSUE TITLE
Send unencoded comma as URL parameter value

### ISSUE THREAD

**Issue by CaselIT** [jakubroztocil/httpie#818]
I'm trying to send an unencoded comma in the value of an url parameter. Using `foo==bar,baz`  will escape the comma with `%2C`. I've tried adding one or more escapes, but does not work (it sends the escapes in the value, percent encoded.)

This applies also to other characters in the url parameter value (like `#`), so the general question is if there is a way to turn off encoding of url parameter values

**Comment by jakubroztocil** [comment]
The `param==value` syntax is meant as a convenience method where you can safely use any string and HTTPie applies URL-escaping as documented in https://httpie.org/doc#querystring-parameters.

```bash
$ http -v httpbin.org/get  f?oo=='foo=bar,baz&bat=bam'
```

```http
GET /get?f%3Foo=foo%3Dbar%2Cbaz%26bat%3Dbam HTTP/1.1
```

If you want to specify the exact URL, then simply avoid the `==` syntax:

```bash
$ http -v httpbin.org/get?foo=bar,baz
```

```http
GET /get?foo==bar,baz HTTP/1.1
```

**Comment by RIZWAN0061** [comment]
Hi brother I needed to Target Facebook account commands

**Comment by CaselIT** [comment]
Ok, makes sense.
Thanks

**Comment by RIZWAN0061** [comment]
I m not understand your talk please explain
