### ISSUE TITLE
Python 3.5 is unsupported, although advertised in setup.py

### ISSUE THREAD

**Issue by vytas7** [jakubroztocil/httpie#836]
Hello!
And thanks for the great HTTP client.

I've noticed an issue with the latest release (`2.0.0`) + CPython 3.5: the Trove classifiers in `setup.py` list Python 3.5 among supported programming languages.
Furthermore, `setup.py` does not define any `python_requires` that could help `Pip` choosing the right version.

However, it seems that `httpie` has already embraced f-strings, which are unsupported on 3.5:
```
  File "<... my virtual env ...>/lib/python3.5/site-packages/httpie/core.py", line 88
    env.log_error(f'Request timed out ({parsed_args.timeout}s).')
```

FWIW, `README.rst` correctly states that 3.6+ is required. But `pip` cannot parse this info :slightly_smiling_face:

**Comment by bsolomon1124** [comment]
Addressed in PR https://github.com/jakubroztocil/httpie/pull/841.

**Comment by jakubroztocil** [comment]
Fixed, thanks.
