### ISSUE TITLE
[2.0.0] "binary data not shown in terminal" fails when used with GitLab CI

### ISSUE THREAD

**Issue by CyberMew** [jakubroztocil/httpie#849]
"binary data not shown in terminal" appears when using on terminal directly, but not when via GitLab CI. It literally dumped the whole file out to the log file, triggering a job fail.

**Comment by jakubroztocil** [comment]
@CyberMew the "binary data not shown in terminal"  feature only  applies when you invoke HTTPie from a terminal. Which is not the case with CI jobs. To prevent the unwanted output, you could redirect the data to `/dev/null` a or use a `HEAD`  request, if possible.
