### ISSUE TITLE
Cookies set to expire in HTTP response are not removed from session file

### ISSUE THREAD

**Issue by rca** [jakubroztocil/httpie#853]
When using the `--session` option and storing a session in a file, when the response includes a `Set-Cookie` header that sets a cookie to a date in the past, the cookie is not cleared out of the session file as I would expect.  Because of this, for example, cookies that are set to expire remain in the session and are still sent in subsequent requests.

Thank you.

**Comment by juped** [comment]
@iamcathal and @csr will be working on this!

**Comment by jakubroztocil** [comment]
Sweet, @juped. I've just written some suggestions   on another sessions-related issue that will be useful here as well:

https://github.com/jakubroztocil/httpie/issues/662#issuecomment-641023598
