### ISSUE TITLE
[Feature request] Support for --ciphers command

### ISSUE THREAD

**Issue by shafr** [jakubroztocil/httpie#870]
It is possible to specify specific cipher that you want to test with in CURL - by using --ciphers. 

At the moment I was not able to find one for httpie. 

Please add one. 

This would allow for testing for obsolete and vulnerable ciphers.

**Comment by ykdui** [comment]
Buy Valid Cvv CC Dumps Track 1/2 CC SSN DOB Track-1/2-FULLZ-Transfer/Western union Bank-Log-In-PayPal-Transfer-and-Log-In Buy/sell CVV CC DOB SSN FULLZ - Dumps Pin...
Telegram.@Ykidven

Cc Format Is
Format is:

Card Number | Exp. Date | CVV/CVV2 | First Name | Last Name | Street | City 
| State | Zip Code | Country | Phone | Type Of Card | Bank Name

I'm Loading All Types Of Paypal Account With No ChargeBacks... Cash app Loading I Can Load All Non Verified Account with No Problem Or Verified PayPal Account..I Even Sell Paypal Logs At Cheap Prices....Pm Me If You Interested In Loading Your Paypal Account
Telegram.@Ykidven

Paypal Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$


CashApp Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 3000$

Telegram@Ykidven

Doing Wu Transfers
I Am Doing Wu Transfer Here And I Need I Very Serious Buyer Who Also Want To Work With Me And Make Money With Me Here...
Note...i will Do The Transfer Then After you Track The Mtcn You Make Payment Before you have the sender's Info

Western Union Price List
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 2500$

Telegram.@Ykidven
Telegram.@Ykidven
Telegram.@Ykidven

ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru

**Comment by jakubroztocil** [comment]
Relevant: https://lukasa.co.uk/2017/02/Configuring_TLS_With_Requests/

**Comment by jakubroztocil** [comment]
@shafr `--ciphers` is now supported in `master`. If you [install the development version](https://httpie.org/docs#unstable-version), then you can test it & provide feedback. It would be interesting to play with `--ciphers` in combination with `--ssl`.

**Comment by jakubroztocil** [comment]
`--ciphers` documentation: https://github.com/jakubroztocil/httpie#ssl-ciphers
