### ISSUE TITLE
& Ampersand issue with GET method

### ISSUE THREAD

**Issue by leoheck** [jakubroztocil/httpie#880]
Hi, I have a website where I can set my wifi SSID and the password. 
Setting with browser, I can fill the form with a password that has `&` characters. This works just fine.

However, I can't set the same with httpie.

I am trying to send this `&` character with the URL parameter `(?q=search)` like:
```
http \
	-v \
	GET http://ip/cgi-bin/configManager.cgi \
	action=='setConfig' \
	ssid=='mywifi' \
	pass=="mypass&"
```

With the verbose mode, I see that the URL becomes like:
```http://ip/cgi-bin/configManager.cgi?action=setconfig&ssid=mywifi&pass=mypass%26```

But, reading what was stored it is `mypass%26` instead of `mypass&` 

What should I do to send an `&` instead of `%26`?

How can I send a password with a & from a website page loaded in browser but I can't do the same using httpie?

**Comment by leoheck** [comment]
I added the same question here, too.
https://amcrest.com/forum/viewtopic.php?f=18&t=13582

**Comment by jakubroztocil** [comment]
@leoheck the param `name==value` notation automatically escapes any special characters in the name and value (https://httpie.org/doc#querystring-parameters). 

Ampersand is a special character here because it is used as the delimiter, so the only way to send a literal ampersand is to URL-escape it (`%26`). 

A correctly behaving server will then unescape the querystring and end up with the correct value.

```bash
$ http 'httpbin.org/get?action=setconfig&ssid=mywifi&pass=mypass%26'
# pass='mypass&'
```

```bash
$ http 'httpbin.org/get?action=setconfig&ssid=mywifi&pass=mypass&'
# pass='mypass'
```

**Comment by leoheck** [comment]
@jakubroztocil you are totally correct. The `&` is the most reserved character in this scenario.

Should I code the `&` manually or the `hhtpie` will do that for me?

In the example you gave me, you are coding the `&` by yourself. I am also doing that, but it does not work like in your example.

**However, your URL example does not look like mine.** It doesn't have the .cgi part. But I have no knowledge enough to say that your example is like the one I gave. But I believe you are not using a CGI. 

The CGI is the important part here because I was able to send the `&` as a value in another example similar to the one you gave me.

So, the final question is:
**Does the CGI need to reverse the encoding by itself? I meant, does it should be programmed like that or it should happen automatically with the get method? IF not, is it something with `httpie` itself?**

**Comment by leoheck** [comment]
This is the only page I found about this subject.
http://xahlee.info/js/url_encoding.html

> Discovered a subtle issue with automating URL encoding. In URL, if you have the ampersand “&” char, and if this URL is to be inside a HTML doc as a link, then, there's no automated procedure that determines correctly whether the char should be encoded as %26 or &amp;.

> If the char is used as part of the file name or path, then it should be encoded as %26, but if it is used as a separator for CGI parameters, then it should be encoded as &amp;.

However the `&amp;` also didn't work for me. I also tested with `%26amp;`. Also, double encoding manually like `%2526` and `%2526amp;`

**Comment by jakubroztocil** [comment]
@leoheck your original command is correct — it uses the `==` syntax, which does the escaping automatically.

**Comment by leoheck** [comment]
Yeah, so, is it possible to disable this by default to test it? I was not able to find a flag that does that.

**Comment by jakubroztocil** [comment]
Yes, just specify the full desired URL without using the `==` notation

```bash
$ http 'httpbin.org/get?action=setconfig&ssid=mywifi&pass=mypass&'
```

**Comment by leoheck** [comment]
Cool, I see. And it will still use the get method, right?

**Comment by jakubroztocil** [comment]
Yup
