### ISSUE TITLE
Documentation example showing how to post raw JSON to some route

### ISSUE THREAD

**Issue by nhooey** [jakubroztocil/httpie#882]
It's not clear from the website's documentation, or the `--help` output, how to do the following equivalent curl task:

**Post a raw JSON query to ElasticSearch:**
```
curl \
    --header "Content-Type: application/json" \
    --request POST \
    --data '{ "_source": [ "restricted_countries.*" ], "query": { "match_all": {} }, "size": 1000 }' \
    'http://localhost:9200/_search'
```

The examples seem to show how to post form values and other stuff.

It would be great if there was a way to do this, and if it was documented in all places, such that searching for "httpie post json" would show the answer in the search result context of Google's top hits.

After a quick read of the documentation, I'm not even sure if it's possible, but I didn't dig that deep.

**Comment by jakubroztocil** [comment]
You are right, this should be made more clear in the docs.

This is how you would make the same request with httpie:

```bash
$ echo '{ "_source": [ "restricted_countries.*" ], "query": { "match_all": {} }, "size": 1000 }'  \
| http :9200/_search
```
I.e.,  pass the raw request data through `stdin`. It’s explained here https://httpie.org/doc#redirected-input

(You don’t need to explicitly specify that you want POST, JSON content-type, nor localhost — those are the defaults.)

**Comment by ykdui** [comment]
Buy Valid Cvv CC Dumps Track 1/2 CC SSN DOB Track-1/2-FULLZ-Transfer/Western union Bank-Log-In-PayPal-Transfer-and-Log-In Buy/sell CVV CC DOB SSN FULLZ - Dumps Pin...
Telegram.@Ykidven

Cc Format Is
Format is:

Card Number | Exp. Date | CVV/CVV2 | First Name | Last Name | Street | City 
| State | Zip Code | Country | Phone | Type Of Card | Bank Name

I'm Loading All Types Of Paypal Account With No ChargeBacks... Cash app Loading I Can Load All Non Verified Account with No Problem Or Verified PayPal Account..I Even Sell Paypal Logs At Cheap Prices....Pm Me If You Interested In Loading Your Paypal Account
Telegram.@Ykidven

Paypal Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$


CashApp Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 3000$

Telegram@Ykidven

Doing Wu Transfers
I Am Doing Wu Transfer Here And I Need I Very Serious Buyer Who Also Want To Work With Me And Make Money With Me Here...
Note...i will Do The Transfer Then After you Track The Mtcn You Make Payment Before you have the sender's Info

Western Union Price List
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 2500$

Telegram.@Ykidven
Telegram.@Ykidven
Telegram.@Ykidven

ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru

**Comment by naeim249** [comment]
ApI /Tokens/Ethereum

**Comment by AHMED0504492442** [comment]
Greetings to you, please, I am a user, I learn from you, please consider, and appreciate mistakes, ... and inform me right and correct

**Comment by AHMED0504492442** [comment]
Please return the hard disk that was compromised by you and crash it and out of the operating system. Why did you do that?

**Comment by jakubroztocil** [comment]
This docs section now addressed how to post raw JSON, etc.:

https://httpie.org/docs#raw-and-complex-json
