### ISSUE TITLE
Last release 2.0.0 on Pypi broke Python deployments older than 3.6

### ISSUE THREAD

**Issue by piroux** [jakubroztocil/httpie#886]
## Results
Right now, installing `httpie` with `pip`, hence from Pypi, with a Python version inferior to Python3.6, it will still select the release `2.0` of `httpie` which won't be compatible.
So, right now, with the current release of the `2.0`, all builds/setups requiring `httpie` and using a Python version inferior to Python 3.6, are breaking, but that should not be the case.

## Context
The release `2.0` of `httpie` broke automated builds and setups for the following reasons:
- The `setup.py` file is missing [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires).
- The upload to Pypi was not done with the right parameters/command so that the wheel for `2.0` is still marked as compatible with Python2 on Pypi whereas it was the first release of `httpie` dropping its support:

![Screenshot from 2020-03-11 12-13-45](https://user-images.githubusercontent.com/438492/76414734-33980100-6398-11ea-86e9-ac12e818f698.png)

## Resolution
What should be done to fix the problem:
- add `python_requires='>=3.6',` in `setup.py` and commit in a seperate release branch where the commit `a7e5228` has been checked out.
- choose a new git tag following semver (if possible) based on the current release tag, so for instance: `2.0.0-post`, `2.0.0-a` or `2.0.0-fix`, etc
- re-upload the new fixed "2.0" release with a new release name (potentially identical to the git tag) on Pypi with the right commands & parameters (see comment below).
- delete the current release `2.0` from Pypi (Better to do it last, in order not to break Python3.6+ deployments while doing those steps to save pre-Python3.6 deployments)

I know that this is no ordinary task. :smiley:

---
I have already helped another maintainer last year in offering to do the same kind of tasks.
For more details on which `setup.py` and `twine` commands to use, please refer to the *Resolution Steps 2 et 3* in that [Issue comment](https://github.com/tlocke/pg8000/issues/7#issue-406228442).

**Comment by jakubroztocil** [comment]
Thanks for the elaborate report, @piroux. I have tried to fix the issue following your tutorial, but I was unable to  get it fully to work. The problem was PyPi not accepting a suffixed version, and also with the package configuration and twine invocation. I would be happy to accept a PR for this. (I have tried a few times and ended up publishing and then deleting v2.0.1).

**Comment by ykdui** [comment]
Buy Valid Cvv CC Dumps Track 1/2 CC SSN DOB Track-1/2-FULLZ-Transfer/Western union Bank-Log-In-PayPal-Transfer-and-Log-In Buy/sell CVV CC DOB SSN FULLZ - Dumps Pin...
Telegram.@Ykidven

Cc Format Is
Format is:

Card Number | Exp. Date | CVV/CVV2 | First Name | Last Name | Street | City 
| State | Zip Code | Country | Phone | Type Of Card | Bank Name

I'm Loading All Types Of Paypal Account With No ChargeBacks... Cash app Loading I Can Load All Non Verified Account with No Problem Or Verified PayPal Account..I Even Sell Paypal Logs At Cheap Prices....Pm Me If You Interested In Loading Your Paypal Account
Telegram.@Ykidven

Paypal Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$


CashApp Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 3000$

Telegram@Ykidven

Doing Wu Transfers
I Am Doing Wu Transfer Here And I Need I Very Serious Buyer Who Also Want To Work With Me And Make Money With Me Here...
Note...i will Do The Transfer Then After you Track The Mtcn You Make Payment Before you have the sender's Info

Western Union Price List
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 2500$

Telegram.@Ykidven
Telegram.@Ykidven
Telegram.@Ykidven

ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru

**Comment by jakubroztocil** [comment]
This is now resolved. 

Releases starting with version 2.1.0 have the correct `python_requires='>=3.6'`. 

The 2.0.0 PyPi package has been [yanked](https://www.python.org/dev/peps/pep-0592/) (it cannot be installed without specifying the exact version — `pip install httpie==2.0.0`).
