### ISSUE TITLE
HTML docs: anchor links broken on mobile

### ISSUE THREAD

**Issue by shanepelletier** [jakubroztocil/httpie#894]
In the HTTPie website's [documentation ](https://httpie.org/doc) there are numerous instances of links to other sections of the documentation that use a standard `<a href="#section-name">`  anchor link. Unfortunately, on at least the Firefox 68.7.0 and Chrome 80 mobile browsers, the links don't jump to the appropriate section when clicked on. The URL of the browser is changed as expected, and reloading the page after clicking on the link loads the page at the appropriate section.

I've done some digging around in the site's HTML; in `/static/dist/app.js` there are two methods that I think may have something to do with the issue: `handleLinkClick` and `handleHashChange`. I suspect that this problem affects any website that uses whatever static site generator HTTPie uses, so a fix here should probably be sent upstream also.

I'll try having a go at fixing the issue once I've slept (it's 5am here) and I'm back at my computer (debugging JS on mobile sounds about as fun as a root canal). If anyone knows what static site generator or HTML documentation generator was used, that would be a big help in getting the fix upstreamed.

**Comment by jakubroztocil** [comment]
@ shanepelletier thank you for the bug report — it should be fixed now.

(In case you are interested, this was the problem: https://stackoverflow.com/questions/8149155/animate-scrolltop-not-working-in-firefox)
