### ISSUE TITLE
Equivalent of path-as-is option in curl

### ISSUE THREAD

**Issue by exploide** [jakubroztocil/httpie#895]
In `curl` there is the `--path-as-is` option:

> Tell curl to not handle sequences of /../ or /./ in the given URL path. Normally curl will squash or merge them according to standards but with this option set you tell it not to do that.

Currently, httpie does not send paths like `/../../../../../` to the server but resolves and removes them locally.

Sending such sequences can be useful during security testing, e.g. checking directory traversal vulnerabilities.

I would like to request a similar option as `curl`'s `--path-as-is`.

**Comment by jakubroztocil** [comment]
The dot segment removal is automatically applied by the upstream `urllib3` library in its [`parse_url()` implementation](https://github.com/urllib3/urllib3/blob/263da24d4b5c33392772e638b12d02e5b07abf9f/src/urllib3/util/url.py#L384). Which is called from requests’s [`PreparedRequest.prepare()`](https://github.com/psf/requests/blob/fd13816d015c4c90ee65297fa996caea6a094ed1/requests/models.py#L380):



Currently, neither library provides a way to disable the normalisation, sadly.

urllib3==1.25.8
requests==2.23.0


---

```bash
$ http --offline example.org/foo/../bar/
```

```http
GET /bar/ HTTP/1.1
```

**Comment by exploide** [comment]
Good to know.

In the meantime, one can partially workaround this by manually URL-encoding `/` as `%2f` if needed.

**Comment by exploide** [comment]
Actually, this was already requested for the `requests` library in https://github.com/psf/requests/issues/5289

The issue contains a solution approved by a maintainer.

**Comment by jakubroztocil** [comment]
@exploide the linked issue includes a comment with a decent workaround, so I’ve just pushed support for `--path-as-is`  to `master`.

**Comment by exploide** [comment]
Awesome. That was fast. Thanks! :+1:
