### ISSUE TITLE
`http: error: InvalidSchema: Missing dependencies for SOCKS support.` despite installing requests[socks]

### ISSUE THREAD

**Issue by coaxial-abraxas** [jakubroztocil/httpie#904]
I followed the documentation's instructions to install `requests[socks]` with `pip -U requests[socks]`, but I'm still getting the error.

```
$ http --version
0.9.8
```

Using Ubuntu 18.04 with the following env vars set:

```
$ env | grep -i proxy
HTTP_PROXY=socks5h://localhost:8118
FTP_PROXY=socks5h://localhost:8118
http_proxy=socks5h://localhost:8118
ALL_PROXY=socks5h://localhost:8118
NO_PROXY=localhost,127.0.0.0/8,::1,company.com
HTTPS_PROXY=socks5h://localhost:8118
RSYNC_PROXY=socks5h://localhost:8118
```

httpie installed with `sudo apt install httpie`

**Comment by jakubroztocil** [comment]
It’s possible that the apt-installed version of HTTPie does not have access to the additional pip-installed packages, for some reason. Also HTTPie 0.9.8 is very old (it might be unrelated, though). I would try to install HTTPie using pip instead.

**Comment by coaxial-abraxas** [comment]
I must be doing something wrong... I tried installing with `pip` after removing using `apt`, but I'm now getting errors when trying to run httpie:

```
$ pip install -U httpie
Collecting httpie
  Using cached https://files.pythonhosted.org/packages/96/42/d2d51ef0d6e9c9ab1c94313f08813ece14bdc3d5b6d8f22abb8fe6f3dad9/httpie-2.0.0-py2.py3-none-any.whl
Collecting Pygments>=2.5.2 (from httpie)
  Using cached https://files.pythonhosted.org/packages/be/39/32da3184734730c0e4d3fa3b2b5872104668ad6dc1b5a73d8e477e5fe967/Pygments-2.5.2-py2.py3-none-any.whl
Collecting requests>=2.22.0 (from httpie)
  Using cached https://files.pythonhosted.org/packages/1a/70/1935c770cb3be6e3a8b78ced23d7e0f3b187f5cbfab4749523ed65d7c9b1/requests-2.23.0-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests>=2.22.0->httpie)
  Using cached https://files.pythonhosted.org/packages/e1/e5/df302e8017440f111c11cc41a6b432838672f5a70aa29227bf58149dc72f/urllib3-1.25.9-py2.py3-none-any.whl
Collecting chardet<4,>=3.0.2 (from requests>=2.22.0->httpie)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.22.0->httpie)
  Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl
Collecting idna<3,>=2.5 (from requests>=2.22.0->httpie)
  Using cached https://files.pythonhosted.org/packages/89/e3/afebe61c546d18fb1709a61bee788254b40e736cff7271c7de5de2dc4128/idna-2.9-py2.py3-none-any.whl
Installing collected packages: Pygments, urllib3, chardet, certifi, idna, requests, httpie
Successfully installed Pygments-2.5.2 certifi-2020.4.5.1 chardet-3.0.4 httpie-2.0.0 idna-2.9 requests-2.23.0 urllib3-1.25.9

$ http --help
Traceback (most recent call last):
  File "/home/user/.local/bin/http", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python2.7/site-packages/httpie/__main__.py", line 10, in main
    from .core import main
  File "/home/user/.local/lib/python2.7/site-packages/httpie/core.py", line 21
    args: List[Union[str, bytes]] = sys.argv,
        ^
SyntaxError: invalid syntax
```

**Comment by jakubroztocil** [comment]
@coaxial-abraxas can you please tell me what Python version you use?

```bash
$ python --version
````

I assume it will be older than the 3.6, which is required by by HTTPie 2.0.0+. The following should work:

```bash
$ pip install 'httpie<2.0.0'
```

(This is indeed a bug: #886)

**Comment by ykdui** [comment]
Buy Valid Cvv CC Dumps Track 1/2 CC SSN DOB Track-1/2-FULLZ-Transfer/Western union Bank-Log-In-PayPal-Transfer-and-Log-In Buy/sell CVV CC DOB SSN FULLZ - Dumps Pin...
Telegram.@Ykidven

Cc Format Is
Format is:

Card Number | Exp. Date | CVV/CVV2 | First Name | Last Name | Street | City 
| State | Zip Code | Country | Phone | Type Of Card | Bank Name

I'm Loading All Types Of Paypal Account With No ChargeBacks... Cash app Loading I Can Load All Non Verified Account with No Problem Or Verified PayPal Account..I Even Sell Paypal Logs At Cheap Prices....Pm Me If You Interested In Loading Your Paypal Account
Telegram.@Ykidven

Paypal Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$


CashApp Transfer Price List
20$ for 250$
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 3000$

Telegram@Ykidven

Doing Wu Transfers
I Am Doing Wu Transfer Here And I Need I Very Serious Buyer Who Also Want To Work With Me And Make Money With Me Here...
Note...i will Do The Transfer Then After you Track The Mtcn You Make Payment Before you have the sender's Info

Western Union Price List
30$ for 350$
40$ for 400$
50$ for 500$
60$ for 600$
70$ for 700$
80$ for 800$
90$ for 950$
100$ for 1500$
200$ for 2500$

Telegram.@Ykidven
Telegram.@Ykidven
Telegram.@Ykidven

ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru
ICQ...clarity.baron@bk.ru

**Comment by coaxial-abraxas** [comment]
For the time being, I have installed it with `python3 -m pip install -U httpie`. My Python3 is 3.6.9, and python is 2.7.17. Now using httpie 2.1.0.

```bash
$ python --version
Python 2.7.17

$ python3 --version
Python 3.6.9

$ http --version
2.1.0
```

**Comment by jakubroztocil** [comment]
HTTPie 2.3.0 will support SOCKS out of the box w/o extra installation.
