### ISSUE TITLE
[Bug Report] there will be a little problem key has trailing whitespaces after `:` when I send the json

### ISSUE THREAD

**Issue by trylovetom** [jakubroztocil/httpie#915]
### Description
I create the node.js express server as backend. When I get the request with json data from httpie, there will be a little different between java, javascript.

### Expected Behavior
**what I get on my server**
```sh
{"hello":"world"}
```

### Actual Behavior
**what I get on my server**
```sh
{"hello": "world"}
---------^--------- trailing whitespaces here
```

There will be a problem, when I use the parser from third party parser such as [turbo-json-parse](https://github.com/mafintosh/turbo-json-parse).

### Environment
- Node.js v14.2.0
- express v4.17.1
- httpie v2.1.0
- macOS (Catalina v10.15.4)
  - MacBook Pro (Retina, 13-inch, Early 2015)
  - 2.7 GHz Core x2
  - 8 GB DDR3 Ram x1

**httpie command**
```sh
http post :3000 hello=world
```

**my source code**
```js
const express = require('express')
const bodyParser = require('body-parser')

// create server
const app = express()

// add middleware
app.use(bodyParser.raw()))
app.use(function (req, res, next) {
  console.log(req.body.toString()) // print the body from client
  next()
})
```

### Relative
- https://stackoverflow.com/questions/16311562/python-json-without-whitespaces

**Comment by lbindal** [comment]
I had the same problem. you can remove spaces from the string as follows
str = str.replace(/\s/g, '');

**Comment by jakubroztocil** [comment]
What is the bug? The JSON HTTPie produces is perfectly valid. 

> I had the same problem. you can remove spaces from the string as follows
> str = str.replace(/\s/g, '');

Again, what problem does this solve? 

Spaces between keys are ignored by JSON parsers.

**Comment by lbindal** [comment]
Jakub, what was happening in my case is I have incoming request in JSON format which has url, method, auth-type, auth, headers etc and i needed to parse that and then dynamically create a httpie command and execute it in my python script. So I did following
parsedJson = json.loads(IncomingJSON)
method = parsedJson ['method']
url = parsedJson ['url']
authType = parsedJson ['auth-type']
auth = parsedJson ['auth']
body = parsedJson ['body']
headers = parsedJson ['headers']

**headerList = ""
for headerVal in headers:
    headerList = headerList + SPACE + json.dumps(headerVal)**

lets say my incoming headers are [{"X-My-Header":"value1"},{"X-Other-Header":"value2"}]
Problem that was happening in my case was my headerList would look like this when i do

print ("headerList= "headerList)

headerList= {"X-My-Header": "value1"} {"X-Other-Header": "value2"}

Note that there is a space after : in above headerlist. I never noticed that was a problem until i tested it by putting in my httpie command. So i had to remove spaces and { as well to make ti work. This below code worked for me. 

headerList = ""
for headerVal in headers:
    headerList = headerList + SPACE + json.dumps(headerVal).replace(" ", "").replace("{","").replace("}", "").replace('"', '')

thats why i suggested in the response to remove spaces from headers. 

I hope that makes sense!

**Comment by lbindal** [comment]
> Spaces between keys are ignored by JSON parsers.

Spaces will be ignored by json parser if there are spaces in header like mentioned in the problem, httpie command would not work. Spaces needs to be removed from header to successfully run httpie command

**Comment by jakubroztocil** [comment]
I’m afraid I still don’t understand.  I might be able to help If you provide:

1. the full HTTPie command you are calling
2. the actual output
3. the expected output
