### ISSUE TITLE
Running HTTPie commands from within AWS lambda written in python 3.8

### ISSUE THREAD

**Issue by lbindal** [jakubroztocil/httpie#919]
I have a very simple python script whcih i am using to run httpie commands

import os
import sys
os.system("http GET https://reqres.in/api/users?page=2")

Above script works perfectly fine. Now I need to run in AWS lambda. Can I do that? Here is my AWS Lambda

import os
import sys

def lambda_handler(event, context):
    os.system("http GET https://reqres.in/api/users?page=2")

It complains that "sh: http: command not found"

**Comment by jakubroztocil** [comment]
Make sure HTTPie is installed. Find out where the `http` executable is located and either include the full path (something like `/usr/local/bin/http`) in your command or ensure that the containing directory is included in `$PATH`. (Btw, you might also need to include [`--ignore-stdin`](https://httpie.org/docs#best-practices).) 

You might be better off with just using `requests.get(' https://reqres.in/api/users?page=2')`, though.

**Comment by lbindal** [comment]
I am getting permission denied for some reason.. any suggestion
import subprocess
def lambda_handler(req, context):
  result = subprocess.call("/opt/python/bin/http GET https://reqres.in/api/users?page=2", shell=True)
  return result

/bin/sh: /opt/python/bin/http: Permission denied

**Comment by jakubroztocil** [comment]
This has more to do with AWS than with HTTPie. 

The normal way to make an HTTP request from a Python app would be to use `requests.get()`. 

Calling an external CLI app via a subprocess for something easily accomplishable directly in Python adds that sort of complexity you are experiencing while providing no upside.

https://requests.readthedocs.io/en/master/
