### ISSUE TITLE
PluginManager: register already loaded `plugin` instead of `entry_point.load()`

### ISSUE THREAD

**Issue by 0x8b** [jakubroztocil/httpie#922]
https://github.com/jakubroztocil/httpie/blob/0c4709410955e6bb4ae6b91c08d1d617def752df/httpie/plugins/manager.py#L34-L36

**Comment by jakubroztocil** [comment]
@0x8b would you elaborate?

**Comment by 0x8b** [comment]
I mean:

```diff
- self.register(entry_point.load())
+ self.register(plugin)
```

**Comment by jakubroztocil** [comment]
This code does what it is designed to do. I don’t think randomly changing without explanation will make it better.
