### ISSUE TITLE
hide errors

### ISSUE THREAD

**Issue by juniorhero** [jakubroztocil/httpie#923]
I would like to hide all errors as such, I am not using the verbose option -v
what to do?

http: error: SSLError: HTTPSConnectionPool(host='', port=): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')"))) while doing GET request to URL:

**Comment by jakubroztocil** [comment]
Yes, error messages need more love. See #815
