### ISSUE TITLE
Add test for auth_plugin and session behaviour 

### ISSUE THREAD

**Issue by kbanc** [jakubroztocil/httpie#937]
I noticed that there doesn't seem to be code coverage for the use of auth plugins (`--auth-type`) in a session. 

Creating an issue to add a test in `test_sessions.py` to cover it.

**Comment by kbanc** [comment]
I want to confirm the desired behaviour of the auth plugin with sessions. 

Let's assume we have an auth plugin class named `plug`. 

If the user sends a request
 ```http --session=test --auth-type=plug --auth=user:password httpbin.org/auth_endpoint```

Should we expect that the next time the request is sent based on the session,  i.e 
``` http --session=test httpbin.org/auth_endpoint```
that the request will use the same `auth-type` and `auth` specified in the first request?

**Comment by jakubroztocil** [comment]
@kbanc yes, that is the intended behavior

**Comment by jakubroztocil** [comment]
@kbanc we spoke about the inline to-dos yesterday, and this one is effectively what you’re now working on:

https://github.com/jakubroztocil/httpie/blob/cd085cbc0d8ce5fd659ccc01996551dcfc149b13/tests/test_auth_plugins.py#L9
