### ISSUE TITLE
--output doesn't save the header? [PS]redirecting stdout has different behavior.

### ISSUE THREAD

**Issue by imba-tjd** [jakubroztocil/httpie#951]
```
  --output FILE, -o FILE
      Save output to FILE instead of stdout. If --download is also set, then only
      the response body is saved to FILE. Other parts of the HTTP exchange are
      printed to stderr.
```

When I read this sentence, I thought using -o without -d would save the header and the body, but it's not.

---

```
http httpbin.org/image/png > image.png
```

This fails on PowerShell 5.1 and pwsh 7.1. But `-o` works, downloading json works, in cmd works, Python 3.8.3 on Debian 11 works.

Environment:

* OS: Windows 10 20H2
* Python: 3.9.0b3 from MS Store
* httpie: 2.2.0

**Comment by jakubroztocil** [comment]
@imba-tjd if [`STDOUT` is redirected](https://httpie.org/docs#redirected-output) or when `--output, -o` is used, then the default is to output only the response body (i.e. it implies`--print=b`). You can still use one of the [output options](https://httpie.org/docs#output-options) to overwrite that, for example:


```bash
$ http --print=hb httpbin.org/image/png > image.png
```
