### ISSUE TITLE
.httpierc file

### ISSUE THREAD

**Issue by DNSGeek** [jakubroztocil/httpie#953]
It would be great to have a dot-rc file somewhere to specify default command line parameters. For instance, if I want to have the default be https instead of http, instead of having to specify it every time as --default-scheme=https, adding
```
default-scheme=https
```
to some config file would rock.

Additionally, having a [DEFAULT] and multiple individual [HOST] blocks would be awesome, and pretty easy to do with configparser.

**Comment by jakubroztocil** [comment]
Hi @DNSGeek,

> It would be great to have a dot-rc file somewhere to specify default command line parameters.

You can create [`~/.config/httpie/config.json`](https://httpie.org/docs#config.) and put your default options there. For example:

```bash
$ cat ~/.config/httpie/config.json

{"default_options": ["--style=fruity"]}
```

> For instance, if I want to have the default be https instead of http, instead of having to specify it every time as --default-scheme=https

HTTPie now actually also ships with an [`https` command](https://httpie.org/docs#request-url), where `https://` is the default prefix:

```bash
$ https httpie.org
```

> Additionally, having a [DEFAULT] and multiple individual [HOST] blocks would be awesome

This is achievable via [sessions](https://httpie.org/docs#sessions).
