### ISSUE TITLE
No way to send quotes in request headers

### ISSUE THREAD

**Issue by stuartio** [jakubroztocil/httpie#955]
To use etags properly with httpie I need to send the header If-None-Match:"myetag" but specifically need the header to contain the quotes. There does not appear to be a way to escape the quotes or enclose them such that the -pH option shows the header with the "" characters intact or the destination server receives them.

**Comment by jakubroztocil** [comment]
@stuartio You just need to make sure to take your shell’s interpretation of quotes in to account.

```bash
$ http httpbin.org/headers 'hello:"world"'
```

**Comment by stuartio** [comment]
So I have done some further research and discovered this works differently between shells. The syntax above only applies properly in bash, possibly other *nix shells but not in Windows. In Windows there are 2 different methods, and they seem to require Python string escaping:
Cmd.exe - http example.com If-None-Match:\"12345\" -pH (quotes escaped in Python style)
Powershell - http example.com If-None-Match:'\"12345\"' -pH (quotes escaped in Python style, whole header value enclosed in single quotes too)

**Comment by jakubroztocil** [comment]
Yes, HTTPie’s docs use BASH-based examples so you need to check with your specific shell if you use something else. HTTPie has no say in how that gets parsed as it sees the data after it’s passed through the shell. You can easily debug this using `echo …`.
